Repository sofastack/sofastack.tech, pull requests merged in 2019-10, with the labels that each got.

#268 Add a new blog
  content/zh/blog/sofa-weekly-20191004/index.md
Labels: area/blog, cla:yes, size/M

#269 Add a new blog
  content/zh/blog/sofa-enclave-confidential-computing/index.md
Labels: area/blog, cla:yes, size/L

#270 Change the SOFABoot version in SOFARPC to a placeholder
  content/zh/projects/sofa-rpc/getting-started-with-sofa-boot/index.md
Labels: area/projects, cla:yes, kind/docs, proj/sofa-rpc, size/S

#271 typo: open source project name
  data/en/footer.toml
  data/zh/footer.toml
Labels: cla:yes, kind/site, size/XS

#272 Modify the page
  content/zh/awesome/_index.md
Labels: cla:yes, size/XS

#273 Add a new blog
  content/zh/blog/sofa-registry-data-fragmentation-synchronization-scheme/index.md
Labels: area/blog, kind/docs, size/L

#274 Modify the blog
  content/zh/blog/sofa-registry-data-fragmentation-synchronization-scheme/index.md
Labels: size/XS

#275 Add a new blog
  content/zh/blog/sofa-weekly-20191011/index.md
Labels: size/M

#276 feat: home page arch animation
  assets/img/home/cd-cloud-native-architecture-en.png
  assets/img/home/cd-cloud-native-architecture-zh.png
  assets/img/home/cd-cloud-native-architecture.png
  assets/js/app.js
  assets/js/modules/animation/arch.js
  assets/js/modules/animation/archState.js
  assets/js/modules/animation/box.js
  assets/js/modules/animation/index.js
  assets/js/modules/search.js
  assets/sass/global.scss
  assets/sass/pages/home.scss
  assets/sass/partials/header.scss
  assets/svg/arch.svg
  data/en/home.toml
  data/zh/home.toml
  layouts/index.html
  layouts/partials/header.html
Labels: cla:yes, kind/site, size/L

#277 Modify SOFAMosn doc
  content/zh/projects/sofa-mosn/overview/index.md
Labels: kind/docs, proj/sofa-mosn, size/S

#278 Update SOFAMosn project name
  content/en/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/_index.md
Labels: cla:yes, size/S

#280 feat: add doc for rocksdb config
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: First-time contributor, cla:yes, kind/docs, proj/sofa-jraft, size/S

#281 Add a new blog
  content/zh/blog/sofa-registry-session-storage/index.md
Labels: size/L

#282 Fix microservices typo
  assets/svg/arch.svg
Labels: cla:yes, size/XS

#283 Add a new blog
  content/zh/blog/ant-financial-native-cloud-financial-architecture/index.md
Labels: size/L

#284 Add a new blog
  content/zh/blog/ant-financial-native-cloud-security-architecture/index.md
Labels: size/L

#285 Add a new blog
  content/zh/blog/sofa-weekly-20191018/index.md
Labels: cla:yes, size/M

#287 Modify the tags
  content/zh/blog/sofa-jraft--rheakv-distributedLock/index.md
  content/zh/blog/sofa-jraft-deep-dive/index.md
  content/zh/blog/sofa-jraft-production-level-algorithm-library/index.md
  content/zh/blog/sofa-registry-deep-dive/index.md
  content/zh/blog/sofa-registry-introduction/index.md
  content/zh/blog/sofa-registry-metaserver-function-introduction/index.md
  content/zh/blog/sofa-registry-service-discovery-optimization/index.md
  content/zh/blog/sofa-rpc-annotation-support/index.md
  content/zh/blog/sofa-rpc-connection-management-heartbeat-analysis/index.md
  content/zh/blog/sofa-rpc-cross-language-support/index.md
  content/zh/blog/sofa-rpc-data-transmission/index.md
  content/zh/blog/sofa-rpc-framework-overall-extension/index.md
  content/zh/blog/sofa-rpc-generalized-call-implementation/index.md
  content/zh/blog/sofa-rpc-graceful-exit/index.md
  content/zh/blog/sofa-rpc-link-tracking/index.md
  content/zh/blog/sofa-rpc-routing-implementation/index.md
  content/zh/blog/sofa-rpc-serialization-comparison/index.md
  content/zh/blog/sofa-rpc-single-machine-fault-culling/index.md
  content/zh/blog/sofa-rpc-synchronous-asynchronous-implementation/index.md
  content/zh/blog/sofa-rpc-threading-model/index.md
Labels: area/blog, cla:yes, size/L

#288 Add a new blog
  content/zh/blog/ant-financial-happy-1024/index.md
Labels: cla:yes, size/L

#291 feat/doc update
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, kind/docs, proj/sofa-jraft, size/L

#292 Add sample code address
  content/en/projects/sofa-boot/quick-start/index.md
  content/zh/projects/sofa-boot/quick-start/index.md
Labels: cla:yes, kind/docs, proj/sofa-boot, size/XS

#293 Add a new blog
  content/zh/blog/ant-financial-managing-large-scale-kubernetes-clusters/index.md
Labels: cla:yes, size/L

#294 Modify the blog
  content/zh/activities/sofa-registry-lab/index.md
Labels: cla:yes, size/S

#295 Add a new activity
  content/zh/activities/sofa-boot-lab/index.md
Labels: area/activities, cla:yes, size/M

#296 modify the blog
  content/zh/activities/sofa-boot-lab/index.md
Labels: cla:yes, size/XS

#297 modify the blog
  content/zh/projects/sofa-registry/terminology/index.md
Labels: cla:yes, size/XS

#298 Add a new activity
  content/zh/activities/sofa-ark-lab/index.md
Labels: cla:yes, size/M
