Repository sofastack/sofastack.tech, pull requests merged in 2019-12, with the labels that each got.

#332 sofajraft 1.3.0 features
  content/zh/projects/sofa-jraft/release-log/index.md
Labels: cla:yes, kind/docs, proj/sofa-jraft, size/S

#333 Add a newblog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-wushi/index.md
Labels: cla:yes, size/L

#334 Rename SOFAMosn to MOSN
  content/en/projects/sofa-mosn/_index.md
  content/en/projects/sofa-mosn/overview/index.md
  content/en/projects/sofa-mosn/quick-start-run-samples/index.md
  content/en/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  content/en/projects/sofa-mosn/quick-start-run-with-sofamesh/mosn-with-service-mesh.png
  content/en/projects/sofa-mosn/quick-start-setup/index.md
  content/en/projects/sofa-mosn/reference-performance-report010/index.md
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/overview/index.md
  content/zh/projects/sofa-mosn/quick-start-run-samples/index.md
  content/zh/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  content/zh/projects/sofa-mosn/quick-start-run-with-sofamesh/mosn-with-service-mesh.png
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/reference-performance-report010/index.md
  content/zh/projects/sofa-mosn/reference-performance-report021/index.md
Labels: cla:yes, proj/sofa-mosn, size/L

#335 Newblog
  content/zh/blog/kubernetes-practice-antfinal-shopping-festival/index.md
Labels: cla:yes, size/L

#336 Newblog
  content/zh/blog/kubernetes-practice-antfinal-shopping-festival/index.md
Labels: cla:yes, size/XS

#338 Added Spring Bean asynchronous initialization chapter
  content/zh/projects/sofa-boot/_index.md
  content/zh/projects/sofa-boot/bean-async-init/index.md
Labels: First-time contributor, cla:yes, size/M

#340 list fix error
  content/zh/projects/sofa-boot/bean-async-init/index.md
Labels: bug, cla:yes, size/XS

#341 Fix typos
  content/en/projects/sofa-bolt/sofa-bolt-handbook/index.md
  content/zh/blog/sofa-rpc-link-tracking/index.md
  content/zh/projects/sofa-bolt/sofa-bolt-handbook/index.md
Labels: cla:yes, kind/docs, size/XS

#342 Update blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part3-operation/index.md
  content/zh/blog/sofa-weekly-20191025/index.md
  content/zh/blog/sofa-weekly-20191115/index.md
  content/zh/blog/sofa-weekly-20191122/index.md
Labels: cla:yes, size/S

#343 Modify the project
  content/en/projects/sofa-tracer/usage-of-dubbo/index.md
  content/en/projects/sofa-tracer/usage-of-httpclient/index.md
  content/en/projects/sofa-tracer/usage-of-mvc/index.md
  content/en/projects/sofa-tracer/usage-of-okhttp/index.md
  content/en/projects/sofa-tracer/usage-of-resttemplate/index.md
  content/zh/projects/sofa-tracer/print-traceid-spanid/index.md
  content/zh/projects/sofa-tracer/roadmap/index.md
  content/zh/projects/sofa-tracer/usage-of-dubbo/index.md
  content/zh/projects/sofa-tracer/usage-of-httpclient/index.md
  content/zh/projects/sofa-tracer/usage-of-mvc/index.md
  content/zh/projects/sofa-tracer/usage-of-okhttp/index.md
  content/zh/projects/sofa-tracer/usage-of-resttemplate/index.md
Labels: cla:yes, size/M

#344 Add a newblog
  content/zh/activities/sofa-channel-9/index.md
  content/zh/blog/sofa-weekly-20191206/index.md
Labels: cla:yes, size/L

#345 New blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part5-gateway/index.md
Labels: cla:yes, size/L

#346 Newactivity
  content/zh/activities/service-mesh-meetup-9/index.md
Labels: area/activities, cla:yes, size/M

#347 doc: add MOSN core concepts
  content/en/projects/sofa-tracer/print-traceid-spanid/index.md
  content/en/projects/sofa-tracer/report-to-zipkin/index.md
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part2-mesh/index.md
  content/zh/blog/sofa-tracer-sampling-tracking-deep-dive/index.md
  content/zh/blog/sofa-tracer-unvarnished-transmission-slf4j-mdc/index.md
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/core-concept/index.md
  content/zh/projects/sofa-mosn/core-concept/mosn-core.jpg
  content/zh/projects/sofa-mosn/core-concept/mosn-goroutine-model.jpg
  content/zh/projects/sofa-mosn/core-concept/mosn-modules-arch.jpg
  content/zh/projects/sofa-mosn/core-concept/mosn-tls-1.png
  content/zh/projects/sofa-mosn/core-concept/mosn-tls-2.png
  content/zh/projects/sofa-mosn/core-concept/netpoll-model.jpg
  content/zh/projects/sofa-mosn/core-concept/raw-epoll-model.jpg
  content/zh/projects/sofa-tracer/report-to-zipkin/index.md
  content/zh/projects/sofa-tracer/roadmap/index.md
  scripts/lint-site.sh
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/L

#348 Newblog
  content/zh/blog/ant-financial-db-mesh-explore-practice/index.md
Labels: cla:yes, size/M

#349 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#350 Add sidecar pattern
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/sidecar-pattern/index.md
  content/zh/projects/sofa-mosn/sidecar-pattern/sidecar-pattern.jpg
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/M

#351 Add Ah Newblog
  content/zh/blog/sofa-weekly-20191213/index.md
Labels: cla:yes, size/L

#352 Newblog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part6-operator/index.md
Labels: cla:yes, size/L

#353 Update MOSN doc
  content/zh/projects/sofa-mosn/core-concept/index.md
Labels: kind/docs, proj/sofa-mosn

#355 Add MOSN configuration docs
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/concept/_index.md
  content/zh/projects/sofa-mosn/concept/core-concept/index.md
  content/zh/projects/sofa-mosn/concept/core-concept/mosn-core.jpg
  content/zh/projects/sofa-mosn/concept/core-concept/mosn-goroutine-model.jpg
  content/zh/projects/sofa-mosn/concept/core-concept/mosn-modules-arch.jpg
  content/zh/projects/sofa-mosn/concept/core-concept/mosn-tls-1.png
  content/zh/projects/sofa-mosn/concept/core-concept/mosn-tls-2.png
  content/zh/projects/sofa-mosn/concept/core-concept/netpoll-model.jpg
  content/zh/projects/sofa-mosn/concept/core-concept/raw-epoll-model.jpg
  content/zh/projects/sofa-mosn/concept/sidecar-pattern/index.md
  content/zh/projects/sofa-mosn/concept/sidecar-pattern/sidecar-pattern.jpg
  content/zh/projects/sofa-mosn/configuration/_index.md
  content/zh/projects/sofa-mosn/configuration/custom/index.md
  content/zh/projects/sofa-mosn/configuration/listener/filter-chain/index.md
  content/zh/projects/sofa-mosn/configuration/listener/network-filter/connection-manager/index.md
  content/zh/projects/sofa-mosn/configuration/listener/network-filter/proxy/index.md
  content/zh/projects/sofa-mosn/configuration/listener/overview/index.md
  content/zh/projects/sofa-mosn/configuration/overview/index.md
  content/zh/projects/sofa-mosn/configuration/server/overview/index.md
Labels: kind/docs, proj/sofa-mosn

#357 Add a new blog
  content/zh/blog/sofa-weekly-20191220/index.md
Labels: cla:yes, size/L

#358 doc: add MOSN traffic hijack solution
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/concept/traffic-hijack/hook-connect.png
  content/zh/projects/sofa-mosn/concept/traffic-hijack/index.md
  content/zh/projects/sofa-mosn/concept/traffic-hijack/iptables.png
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/M

#359 Update images URLs
  content/zh/projects/sofa-mosn/concept/traffic-hijack/index.md
  content/zh/projects/sofa-mosn/concept/traffic-hijack/service-call-process.png
  content/zh/projects/sofa-mosn/concept/traffic-hijack/traffic-hijacking.jpg
Labels: kind/docs, proj/sofa-mosn

#360 SOFAJRaft new features
  content/zh/projects/sofa-jraft/overview/index.md
Labels: cla:yes, size/S

#361 Add new end user.
  content/zh/awesome/_index.md
Labels: cla:yes, size/XS

#362 Add a new blog
  content/zh/blog/sidacar-kubecon-na2019/index.md
Labels: cla:yes, size/L

#363 Add a new blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part7-control-plane/index.md
Labels: cla:yes, size/L

#364 Add a new page
  config.toml
  content/zh/community/index.md
Labels: cla:yes, size/L

#365 Try to fix SOFAJRaft overview doc style
  content/zh/projects/sofa-jraft/overview/index.md
Labels: First-time contributor, bug, cla:no, size/S

#366 Modify the blog
  content/zh/community/index.md
Labels: cla:yes, size/XS

#367 Add MOSN TLS
  content/en/projects/sofa-mosn/_index.md
  content/en/projects/sofa-mosn/overview/index.md
  content/en/projects/sofa-mosn/quick-start-run-samples/index.md
  content/en/projects/sofa-mosn/release-notes/index.md
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/concept/tls/certificate-request-process.png
  content/zh/projects/sofa-mosn/concept/tls/index.md
  content/zh/projects/sofa-mosn/concept/tls/mosn-certificate-arch.png
  content/zh/projects/sofa-mosn/overview/index.md
  content/zh/projects/sofa-mosn/quick-start-run-samples/index.md
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/release-notes/index.md
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/M

#368 Change tab orders and fix typos
  config.toml
  content/zh/community/_index.md
Labels: kind/site

#369 Update diagram
  content/zh/projects/sofa-mosn/concept/traffic-hijack/index.md
  content/zh/projects/sofa-mosn/concept/traffic-hijack/traffic-hijacking.jpg
  content/zh/projects/sofa-mosn/concept/traffic-hijack/traffic-hijacking.png
Labels: cla:yes, size/XS

#370 change level
  content/zh/projects/sofa-mosn/_index.md
Labels: cla:yes, size/XS

#371 Add a new blog
  content/zh/blog/sofa-weekly-20191227/index.md
Labels: cla:yes, size/L

#372 modify mosn quick start document
  content/en/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
Labels: cla:yes, size/M

#376 Modify the blog
  data/zh/home.toml
Labels: cla:yes, size/XS

#378 Fix https://github.com/sofastack/sofastack.tech/issues/373
  content/en/projects/sofa-bolt/sofa-bolt-contribution/index.md
  content/zh/projects/sofa-bolt/sofa-bolt-contribution/index.md
Labels: bug, cla:yes, size/M

#374 (feat) Adds jraft learner guide
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, kind/docs, proj/sofa-jraft, size/S

#377 SOFAJRaft support SSL/TLS
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, kind/docs, proj/sofa-jraft, size/M

#380 Update _index.md
  content/zh/hr/_index.md
Labels: cla:yes, size/L

#381 Modify the blog
  content/zh/hr/_index.md
  data/zh/footer.toml
Labels: cla:yes, size/L

#383 Modify the blog
  data/zh/footer.toml
Labels: cla:yes, size/XS

#384 Add a new blog
  content/zh/blog/knative-serverless-kubecon-na2019/index.md
Labels: cla:yes, size/L
