Repository sofastack/sofastack.tech, pull requests merged in 2019-08, with the labels that each got.

#177 doc: update SOFAMosn fix #173
  content/en/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  content/zh/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
Labels: area/projects, bug, cla:yes, kind/docs, proj/sofa-mosn

#178 Add a new blog
  content/zh/blog/sofa-weekly-20190802/index.md
Labels: area/blog, cla:yes, kind/docs, size/L

#179 doc: update description of the road-map
  content/zh/projects/sofa-bolt/sofa-bolt-roadmap/index.md
Labels: cla:yes, kind/docs, proj/sofa-bolt, size/S

#180 Add a new blog
  content/zh/blog/sofa-jraft-pipeline-principle/index.md
Labels: area/blog, cla:yes, kind/docs, size/L

#181 Fix the tags of the blog
  content/zh/blog/sofa-jraft-algorithm-storage-module-deep-dive/index.md
Labels: bug, cla:yes, kind/docs, size/XS

#182 Fix the tags of the blog
  content/zh/blog/sofa-jraft-deep-dive/index.md
Labels: bug, cla:yes, kind/docs, size/XS

#183 Fix the tags of the blogs
  content/zh/blog/sofa-jraft-algorithm-storage-module-deep-dive/index.md
  content/zh/blog/sofa-jraft-election-mechanism/index.md
  content/zh/blog/sofa-jraft-linear-consistent-read-implementation/index.md
  content/zh/blog/sofa-jraft-pipeline-principle/index.md
  content/zh/blog/sofa-jraft-rheaKV-multi-raft-group/index.md
  content/zh/blog/sofa-jraft-rheakv/index.md
Labels: bug, cla:yes, kind/docs, size/M

#184 Fix the tags of the blogs
  content/zh/blog/sofa-blot-connection-management-deep-dive/index.md
  content/zh/blog/sofa-bolt-codec-deep-dive/index.md
  content/zh/blog/sofa-bolt-framework-deep-dive/index.md
  content/zh/blog/sofa-bolt-serialization-deep-dive/index.md
  content/zh/blog/sofa-bolt-timeout-and-heart-beat-deep-dive/index.md
Labels: bug, cla:yes, kind/docs, size/M

#185 Fix the tags of the blogs
  content/zh/blog/sofa-tracer-event-tracing-deep-dive/index.md
  content/zh/blog/sofa-tracer-overview/index.md
  content/zh/blog/sofa-tracer-response-mechanism/index.md
  content/zh/blog/sofa-tracer-sampling-tracking-deep-dive/index.md
  content/zh/blog/sofa-tracer-unvarnished-transmission-slf4j-mdc/index.md
Labels: bug, cla:yes, kind/docs, size/L

#187 chore: disable legacy website
  config.toml
Labels: cla:yes, kind/site, size/XS

#188 Add a new blog
  content/zh/blog/sofa-weekly-20190809/index.md
Labels: area/blog, cla:yes, kind/docs, size/M

#189 feat: sprint-1.3-part-1
  assets/js/app.js
  assets/js/iconfont.js
  assets/js/modules/aside.js
  assets/js/modules/menu.js
  assets/js/modules/search.js
  assets/js/modules/toc.js
  assets/js/modules/utils.js
  assets/sass/components/layout.scss
  assets/sass/components/list.scss
  assets/sass/components/overlay.scss
  assets/sass/main.scss
  assets/sass/pages/404.scss
  assets/sass/pages/home.scss
  assets/sass/pages/search.scss
  assets/sass/partials/aside.scss
  assets/sass/partials/header.scss
  assets/sass/partials/post/meta.scss
  assets/sass/partials/toc.scss
  assets/sass/utils/mixins.scss
  assets/sass/utils/variables.scss
  content/en/search/_index.md
  content/zh/search/_index.md
  i18n/en.toml
  i18n/zh.toml
  layouts/_default/search.html
  layouts/guides/single.html
  layouts/partials/aside/code.html
  layouts/partials/aside/toc.html
  layouts/partials/card/toc_list_card.html
  layouts/partials/header.html
  layouts/partials/toc/toc.html
  layouts/partials/toc/toc_leaf.html
  layouts/projects/list.html
  package.json
Labels: cla:yes, kind/site, size/XL

#190 Add hire page
  content/zh/hr/_index.md
Labels: cla:yes, size/M

#192 doc: fix sofajraft content
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/release-log/index.md
Labels: bug, cla:no, kind/docs, proj/sofa-jraft, size/S

#191 chore: fix a typo
  content/zh/blog/service-mesh-meetup-5-istio-retrospect/index.md
Labels: bug, cla:yes, kind/docs, size/XS

#193 Add new end user and new contributors.
  content/zh/awesome/_index.md
Labels: cla:yes, size/M

#194 Add a new blog
  content/zh/blog/sofa-jraft-user-china-mobile/index.md
Labels: cla:yes, kind/docs, size/L

#195 Add a new blog
  content/zh/blog/sofa-meetup-3-seata-retrospect/index.md
Labels: cla:yes, kind/docs, size/L

#196 Fix the title of the blog
  content/zh/activities/sofa-meetup-3/index.md
Labels: cla:yes, kind/docs, size/XS

#197 Add a new activity
  content/zh/activities/sofa-channel-8/index.md
Labels: cla:yes, size/M

#199 chore: fix linting errors
  content/en/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  content/zh/blog/financial-technology-meet-open-source/index.md
  content/zh/blog/sofa-jraft-pipeline-principle/index.md
  content/zh/blog/sofa-jraft-user-china-mobile/index.md
  content/zh/projects/sofa-acts/usage-ide/index.md
  content/zh/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  scripts/lint-site.sh
Labels: cla:yes, kind/docs, size/M

#201 Add a new blog
  content/zh/blog/sofa-weekly-20190816/index.md
Labels: cla:yes, kind/docs, size/M

#200 feat: sprint-1.3-part-2
  assets/img/cover-light.jpg
  assets/img/cover.jpg
  assets/img/cover.png
  assets/img/logo.png
  assets/img/logo.svg
  assets/js/app.js
  assets/js/modules/pagination.js
  assets/sass/components/layout.scss
  config.toml
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/guides/list.html
  layouts/partials/card/guide_card.html
  layouts/partials/card/project_card.html
  layouts/partials/head.html
  layouts/partials/header.html
  layouts/partials/pagination/pagination.html
  layouts/projects/list.html
  package.json
  webpack.config.js
Labels: cla:yes, kind/site, size/L

#202 Update index.md
  content/zh/projects/sofa-boot/modular-development/index.md
Labels: First-time contributor, cla:yes, size/XS

#203 sofajraft 1.2.6 features
  content/zh/projects/sofa-jraft/jraft-rheakv-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/release-log/index.md
Labels: First-time contributor, cla:yes, kind/docs, size/L

#205 Add a new blog
  content/zh/blog/sofa-meetup-3-cloud-original-retrospect/index.md
Labels: area/blog, cla:yes, size/L

#206 Add a new activity
  content/zh/activities/sofa-channel-4/index.md
Labels: area/activities, cla:yes, size/M

#208 Add a new activity
  content/zh/activities/sofa-channel-6/index.md
Labels: area/activities, cla:yes, size/M

#209 Fix the blog
  content/zh/activities/sofa-channel-6/index.md
Labels: area/blog, cla:yes, size/M

#210 Fix the blogs' mata data
  content/zh/activities/sofa-channel-1/index.md
  content/zh/activities/sofa-channel-2/index.md
  content/zh/activities/sofa-channel-3/index.md
  content/zh/activities/sofa-channel-4/index.md
  content/zh/activities/sofa-channel-5/index.md
  content/zh/activities/sofa-channel-7/index.md
  content/zh/activities/sofa-channel-8/index.md
  content/zh/activities/sofa-meetup-2/index.md
  content/zh/activities/sofa-meetup-3/index.md
Labels: area/blog, bug, cla:yes, size/S

#211 Fix the activities matedata config typos
  content/zh/activities/sofa-channel-1/index.md
  content/zh/activities/sofa-channel-2/index.md
  content/zh/activities/sofa-channel-3/index.md
  content/zh/activities/sofa-channel-4/index.md
  content/zh/activities/sofa-channel-5/index.md
  content/zh/activities/sofa-channel-6/index.md
  content/zh/activities/sofa-channel-7/index.md
Labels: area/activities, bug, cla:yes, size/M

#212 Fix a the activity metadata typo
  content/zh/activities/sofa-channel-3/index.md
Labels: area/activities, cla:yes, size/XS

#213 Add a new blog
  content/zh/blog/sofa-channel-5-retrospect/index.md
Labels: area/blog, cla:yes, size/L

#214 Add a new activity
  content/zh/activities/sofa-meetup-1/index.md
Labels: area/blog, cla:yes, size/M

#216 doc: update the doc of sofa-registry
  content/zh/projects/sofa-registry/deployment/index.md
Labels: area/projects, cla:yes, size/XS

#217 Add a new blog
  content/zh/blog/sofa-weekly-20190823/index.md
Labels: area/blog, cla:yes, size/L

#218 Fix SOFARegistry document bug
  content/zh/projects/sofa-rpc/registry-sofa/index.md
Labels: bug, cla:yes, size/S

#219 Delete a duplicate blog
  content/zh/blog/seata-tcc-deep-dive/index.md
  content/zh/blog/seata-tcc-deep-dive/sofa-channel-4.jpg
Labels: cla:yes, size/L

#220 update dashboard doc
  content/zh/projects/sofa-dashboard/ark-console/index.md
  content/zh/projects/sofa-dashboard/dashboard-client/index.md
  content/zh/projects/sofa-dashboard/governance/index.md
  content/zh/projects/sofa-dashboard/quick-start/index.md
Labels: First-time contributor, cla:yes, size/L

#221 Fix acts doc
  content/zh/projects/sofa-acts/usage-ide/index.md
Labels: bug, cla:yes, size/XS

#223 Add a new blog
  content/zh/blog/service-mesh-development-trend-2/index.md
Labels: area/blog, cla:yes, size/L

#222 Add Email contact
  data/en/footer.toml
  data/zh/footer.toml
Labels: cla:yes, kind/site, size/XS

#225 FIX: pagination baseurl
  assets/js/modules/pagination.js
  layouts/partials/pagination/pagination.html
Labels: bug, cla:yes, kind/site, size/S

#226 Add new end user.
  content/zh/awesome/_index.md
Labels: cla:yes, size/XS

#227 Modify the title of the blog
  content/zh/activities/sofa-channel-8/index.md
Labels: cla:yes, size/XS

#228 Add a new blog
  content/zh/blog/sofa-weekly-20190830/index.md
Labels: cla:yes, size/M
