Repository sofastack/sofastack.tech, pull requests merged in 2019-09, with the labels that each got.

#229 Add sofa-ark to tool-projects.
  content/en/projects/sofa-ark/_index.md
  content/en/projects/sofa-jraft/_index.md
  content/zh/projects/sofa-acts/_index.md
  content/zh/projects/sofa-ark/_index.md
  content/zh/projects/sofa-jraft/_index.md
Labels: cla:yes, size/S

#230 Add a new blog
  content/zh/blog/sofa-channel-8-retrospect/index.md
Labels: cla:yes, size/L

#231 Modify the blog
  content/zh/blog/sofa-channel-8-retrospect/index.md
Labels: cla:yes, size/XS

#232 modify the cover
  content/zh/blog/sofa-channel-8-retrospect/index.md
Labels: cla:yes, size/XS

#234 Add a new blog
  content/zh/blog/sofa-rpc-generalized-call-implementation/index.md
Labels: cla:yes, size/L

#235 Add a new blog
  content/zh/blog/sofa-rpc-annotation-support/index.md
Labels: cla:yes, size/L

#236 Add a module of SOFALab
  content/zh/awesome/_index.md
Labels: cla:yes, size/S

#237 Add a new activity
  content/zh/activities/sofa-registry-lab/index.md
Labels: cla:yes, size/M

#240 modify the blog
  content/zh/awesome/_index.md
Labels: cla:yes, size/S

#241 update tracer log doc
  content/zh/projects/sofa-tracer/configuration/index.md
  content/zh/projects/sofa-tracer/log-format-datasource/index.md
  content/zh/projects/sofa-tracer/log-format-dubbo/index.md
  content/zh/projects/sofa-tracer/log-format-httpclient/index.md
  content/zh/projects/sofa-tracer/log-format-okhttp/index.md
  content/zh/projects/sofa-tracer/log-format-openfeign/index.md
  content/zh/projects/sofa-tracer/log-format-resttemplate/index.md
  content/zh/projects/sofa-tracer/log-format-springmvc/index.md
  content/zh/projects/sofa-tracer/usage-of-datasource/index.md
  content/zh/projects/sofa-tracer/usage-of-dubbo/index.md
  content/zh/projects/sofa-tracer/usage-of-httpclient/index.md
  content/zh/projects/sofa-tracer/usage-of-mvc/index.md
  content/zh/projects/sofa-tracer/usage-of-okhttp/index.md
  content/zh/projects/sofa-tracer/usage-of-openfeign/index.md
  content/zh/projects/sofa-tracer/usage-of-resttemplate/index.md
Labels: cla:yes, size/L

#242 fix sofa-tracer index setting
  content/zh/projects/sofa-tracer/_index.md
  content/zh/projects/sofa-tracer/configuration/index.md
Labels: bug, cla:yes, kind/docs, proj/sofa-tracer, size/XS

#243 Add flexible tracer doc
  content/zh/projects/sofa-tracer/_index.md
  content/zh/projects/sofa-tracer/flexible/index.md
  content/zh/projects/sofa-tracer/print-traceid-spanid/index.md
  content/zh/projects/sofa-tracer/reporter-custom/index.md
Labels: cla:yes, kind/docs, proj/sofa-tracer, size/L

#244 Update SOFATracer doc
  content/zh/projects/sofa-tracer/flexible/index.md
Labels: cla:yes, kind/docs, proj/sofa-tracer, size/XS

#245 fix some linting errors and disable html, external hash check
  content/en/projects/sofa-acts/getting-started/index.md
  content/en/projects/sofa-acts/usage-ide/index.md
  content/en/projects/sofa-jraft/jraft-rheakv-user-guide/index.md
  content/zh/blog/service-mesh-development-trend-2/index.md
  content/zh/blog/sofa-channel-5-retrospect/index.md
  content/zh/blog/sofa-rpc-link-tracking/index.md
  scripts/lint-site.sh
Labels: cla:yes, size/M

#246 Add a new blog
  content/zh/blog/sofa-weekly-20190906/index.md
Labels: area/blog, cla:yes, size/M

#247 Modify the blog
  content/zh/activities/sofa-registry-lab/index.md
Labels: area/blog, cla:yes, size/XS

#248 Update the blog
  content/zh/blog/sofa-weekly-20190906/index.md
Labels: area/blog, cla:yes, size/XS

#249 provider dubbo 2.6.x and basic principle
  content/zh/projects/sofa-tracer/usage-of-dubbo/index.md
Labels: cla:yes, proj/sofa-tracer, size/M

#250 Add a new blog
  content/zh/blog/sofa-activity-retrospect-collection/index.md
Labels: area/blog, cla:yes, size/L

#251 Modify the description
  content/zh/blog/sofa-activity-retrospect-collection/index.md
Labels: area/blog, cla:yes, size/XS

#252 ignore two site while linting
  content/zh/blog/sofa-meetup-3-cloud-original-retrospect/index.md
  scripts/lint-site.sh
Labels: cla:yes, size/XS

#255 Replace a mid-autumn festival image
  content/zh/blog/sofa-weekly-20190913/index.md
  scripts/lint-site.sh
Labels: cla:yes, size/XS

#256 Add a new blog
  content/zh/blog/sofa-jraft--rheakv-distributedLock/index.md
Labels: area/blog, cla:yes, size/L

#257 fix markdown style
  content/zh/projects/sofa-boot/sofa-ark-readme/index.md
  scripts/lint-site.sh
Labels: cla:yes, size/XS

#258 Add a new blog
  content/zh/blog/alipay-deep-learning-tensorflow-elasticdl/index.md
Labels: area/blog, cla:yes, size/L

#259 Add a new blog
  content/zh/blog/sofa-weekly-20190920/index.md
Labels: area/blog, cla:yes, size/M

#260 Modify the blog
  content/zh/blog/sofa-weekly-20190920/index.md
Labels: cla:yes, size/XS

#261 feat: home page animation & search pagination
  assets/js/app.js
  assets/js/i18n.js
  assets/js/modules/animition.js
  assets/js/modules/aside.js
  assets/js/modules/pagination.js
  assets/js/modules/search.js
  assets/js/modules/utils.js
  assets/sass/components/layout.scss
  assets/sass/pages/home.scss
  assets/sass/pages/search.scss
  assets/sass/partials/aside.scss
  assets/sass/utils/variables.scss
  assets/svg/box.svg
  assets/svg/float/debris-1.svg
  assets/svg/float/debris-2.svg
  assets/svg/float/debris-3.svg
  i18n/en.toml
  i18n/zh.toml
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/guides/list.html
  layouts/index.html
  layouts/partials/aside/tags.html
  layouts/partials/head.html
  layouts/projects/list.html
  package.json
  webpack.config.js
Labels: cla:yes, kind/site, size/XL

#262 Add a new blog
  content/zh/blog/sofajraft-snapshot-principle-analysis/index.md
Labels: area/blog, cla:yes, size/L

#263 Update release time
  content/zh/blog/sofajraft-snapshot-principle-analysis/index.md
  scripts/install-dependency.sh
Labels: cla:yes, kind/site, size/XS

#265 Update folder name
  content/zh/blog/sofa-jraft-snapshot-principle-analysis/index.md
Labels: cla:yes, size/XS

#266 Add a new blog
  content/zh/blog/sofa-weekly-20190927/index.md
Labels: area/blog, cla:yes, size/L

#267 Add a new blog
  content/zh/blog/sqlflow-ai-didi-antfin-open-source-construction/index.md
Labels: cla:yes, size/M
