Repository sofastack/sofastack.tech, pull requests merged in 2019-11, with the labels that each got.

#301 Add a new blog
  content/zh/blog/sofa-weekly-20191101/index.md
Labels: area/blog, cla:yes, size/M

#302 Update contributors.
  content/zh/awesome/_index.md
Labels: cla:yes, size/M

#303 Add a new blog
  content/zh/blog/seata-saga-flexible-financial-applications/index.md
Labels: area/blog, cla:yes, size/L

#304 update sofa-mosn quick start setup
  content/en/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
Labels: area/projects, cla:yes, proj/sofa-mosn, size/L

#305 Add a new blog
  content/zh/blog/service-mesh-antfin-deep-practice-qcon/index.md
Labels: cla:yes, size/L

#306 Update SOFAMosn docs
  content/en/projects/sofa-mosn/overview/index.md
  content/en/projects/sofa-mosn/quick-start-run-samples/index.md
  content/en/projects/sofa-mosn/quick-start-setup/index.md
  content/en/projects/sofa-mosn/reference-performance-report010/index.md
  content/zh/awesome/_index.md
  content/zh/blog/sofa-rpc-framework-overall-extension/index.md
  content/zh/projects/sofa-mosn/overview/index.md
  content/zh/projects/sofa-mosn/quick-start-run-samples/index.md
  content/zh/projects/sofa-mosn/quick-start-run-with-sofamesh/index.md
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/reference-performance-report010/index.md
  content/zh/projects/sofa-mosn/reference-performance-report021/index.md
Labels: area/projects, cla:yes, kind/docs, proj/sofa-mosn, size/XL

#307 Add a new blog
  content/zh/blog/antfin-service-mesh-network-agents/index.md
Labels: area/blog, cla:yes, size/L

#308 Add SOFAMosn release notes link
  content/en/projects/sofa-mosn/_index.md
  content/en/projects/sofa-mosn/release-notes/index.md
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/quick-start-setup/index.md
  content/zh/projects/sofa-mosn/release-notes/index.md
Labels: cla:yes, proj/sofa-mosn, size/S

#310 Add a new blog
  content/zh/blog/sofa-weekly-20191108/index.md
Labels: cla:yes, size/M

#309 feat: video shortcode
  assets/sass/partials/post/markdown.scss
  layouts/shortcodes/video.html
Labels: cla:yes, size/XS

#311 Add a new activity
  content/zh/activities/service-mesh-meetup-8/index.md
Labels: cla:yes, size/M

#312 Modify the blog
  content/zh/activities/service-mesh-meetup-8/index.md
Labels: cla:yes, size/XS

#313 Update reviewers list
  .github/auto_assign.yml
Labels: cla:yes, size/XS

#314 Add a new blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part1-core/index.md
Labels: cla:yes, size/L

#317 Modify the blog
  content/zh/blog/alipay-deep-learning-tensorflow-elasticdl/index.md
Labels: cla:yes, size/XS

#318 Modify the blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part1-core/index.md
Labels: cla:yes, size/XS

#319 Add a new blog
  content/zh/blog/sofa-weekly-20191115/index.md
Labels: cla:yes, size/L

#321 Add a Newblog
  content/zh/blog/service-mesh-practice-antfinal-shopping-festival-big-exam/index.md
Labels: cla:yes, size/L

#322 Add two blogs
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part2-mesh/index.md
  content/zh/blog/sofa-weekly-20191122/index.md
Labels: cla:yes, size/L

#320 File name mistake described
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: First-time contributor, cla:no, size/XS

#323 Update contributors and others.
  content/zh/awesome/_index.md
Labels: cla:yes, size/M

#324 Newactivity
  content/zh/activities/service-mesh-meetup-8/index.md
  content/zh/activities/sofa-channel-9/index.md
Labels: cla:yes, size/M

#325 Newblog
  content/zh/activities/sofa-channel-9/index.md
Labels: cla:yes, size/XS

#326 Newblog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part3-operation/index.md
Labels: cla:yes, size/L

#327 Newblog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part2-mesh/index.md
Labels: cla:yes, size/XS

#329 Add a new blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part4-rpc/index.md
Labels: cla:yes, size/L

#328 Add spring&#39;s context xsd, otherwise the application won&#39;t start
  content/zh/projects/sofa-boot/dependency-management/index.md
Labels: First-time contributor, cla:no, size/XS

#330 Newblog
  content/zh/blog/sofa-weekly-20191129/index.md
Labels: cla:yes, size/L

#331 modify the blog
  content/zh/blog/sofa-weekly-20191129/index.md
Labels: cla:yes, size/XS
