Repository sofastack/sofastack.tech, pull requests merged in 2020-02, with the labels that each got.

#407 Fix spelling mistakes
  content/en/projects/sofa-rpc/getting-started-with-rpc/index.md
Labels: First-time contributor, cla:no, kind/docs, proj/sofa-rpc, size/XS

#408 Add a new job
  content/zh/hr/_index.md
Labels: cla:yes, size/S

#409 Modify the blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part8-quantity/index.md
Labels: cla:yes, size/XS

#410 Modify a new blog
  content/zh/blog/sofa-weekly-20200207/index.md
Labels: cla:yes, size/L

#411 Modify a new blog
  content/zh/blog/sofa-boot-overview/index.md
Labels: cla:yes, size/L

#412 Modify a new activity
  content/zh/activities/sofa-channel-12/index.md
Labels: cla:yes, size/M

#414 Update MOSN doc link
  content/zh/projects/mosn/_index.md
Labels: cla:yes, kind/docs, proj/mosn, size/XS

#415 Add a new blog
  content/zh/blog/sofa-weekly-20200214/index.md
Labels: cla:yes, size/L

#416 Add a new blog
  content/zh/service-mesh-end-user-survey-report/index.md
Labels: cla:yes, size/M

#420 Modify the blog
  content/zh/blog/sofa-boot- log-isolation/index.md
Labels: cla:yes, size/XS

#421 Remove an incorrect space in the jraft document
  content/zh/projects/sofa-jraft/counter-example/index.md
Labels: First-time contributor, cla:no, size/XS

#422 Modify the blog
  content/zh/blog/sofa-channel-11-retrospect/index.md
Labels: cla:yes, size/L

#423 Update the data
  content/zh/projects/sofa-rpc/faq/index.md
Labels: cla:yes, size/XS

#424 Announcement of SOFAMesh deprecation
  content/en/projects/sofa-mesh/overview/index.md
  content/zh/projects/sofa-mesh/overview/index.md
Labels: cla:yes, size/M

#425 Modify the blog
  content/zh/blog/sofa-channel-11-retrospect/index.md
Labels: cla:yes, size/XS
