Repository sofastack/sofastack.tech, pull requests merged in 2020-01, with the labels that each got.

#385 Add a new activity
  content/zh/activities/service-mesh-meetup-9/index.md
  content/zh/activities/sofa-channel-10/index.md
Labels: cla:yes, size/M

#386 Add a new blog
  content/zh/activities/sofa-channel-10/index.md
  content/zh/blog/sofa-registry-service-offline-notification/index.md
Labels: cla:yes, size/L

#387 Modify the blog
  content/zh/blog/sofa-registry-service-offline-notification/index.md
Labels: cla:yes, size/XS

#388 Add a new blog
  content/zh/blog/knative-serverless-kubecon-na2019/index.md
  content/zh/blog/sofa-weekly-20200103/index.md
Labels: cla:yes, size/L

#389 Add a new blog
  content/zh/blog/sofa-ark-overview/index.md
Labels: cla:yes, size/L

#390 Modify the blog
  content/zh/activities/sofa-ark-lab/index.md
  content/zh/activities/sofa-boot-lab/index.md
Labels: cla:yes, size/S

#391 Fix issue #379
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, kind/docs, proj/sofa-jraft, size/S

#393 Update style
  content/zh/projects/sofa-mosn/concept/tls/index.md
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/XS

#394 Add a new blog
  content/zh/blog/sofa-channel-10-retrospect/index.md
Labels: cla:yes, size/L

#395 Add a new blog
  content/zh/blog/sofa-weekly-20200110/index.md
Labels: cla:yes, size/M

#396 doc: add MOSN smooth upgrade deep dive
  content/zh/projects/sofa-mosn/_index.md
  content/zh/projects/sofa-mosn/concept/nginx-envoy-mosn-hot-upgrade/index.md
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/index.md
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/interaction-process-timeline.png
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/interaction-process.png
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/long-connection-migrating-process.png
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/normal-process.png
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/remaining-responses-migrating-process.png
  content/zh/projects/sofa-mosn/concept/smooth-upgrade/reqeust-smooth-upgrade-process.png
Labels: kind/docs, proj/sofa-mosn, size/XL

#398 Add a new blog
  content/zh/blog/java-kubernetes-operator-kubecon-na2019/index.md
Labels: cla:yes, size/M

#399 Modify the blog
  content/zh/blog/java-kubernetes-operator-kubecon-na2019/index.md
Labels: cla:yes, size/XS

#400 Add a new blog
  content/zh/blog/sofa-weekly-20200117/index.md
Labels: cla:yes, size/M

#401 Update list style
  content/zh/projects/sofa-mosn/concept/core-concept/index.md
Labels: cla:yes, kind/docs, proj/sofa-mosn, size/XS

#402 Add a new blog
  content/zh/activities/sofa-channel-11/index.md
Labels: cla:yes, size/M

#403 Modify the blog
  content/zh/activities/sofa-channel-10/index.md
Labels: cla:yes, size/XS

#404 Add a new blog
  content/zh/blog/service-mesh-practice-in-production-at-ant-financial-part8-quantity/index.md
Labels: cla:yes, size/L

#405 Add a new blog
  content/zh/blog/service-mesh-meetup-9-retrospect-technical-risk-practice/index.md
Labels: cla:yes, size/L
