Repository sofastack/sofastack.tech, pull requests merged in 2020-10, with the labels that each got.

#576 Update contributors.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#577 Add a new blog
  content/zh/blog/sofa-weekly-20201016/index.md
Labels: cla:yes, size/L

#578 Add a new blog
  content/zh/blog/sofa-weekly-20201023/index.md
Labels: cla:yes, size/L

#579 Update the blog
  content/zh/blog/sofa-weekly-20201023/index.md
Labels: cla:yes, size/XS

#580 Add a new blog
  content/zh/sofa-weekly-20201030/index.md
Labels: cla:yes, size/M
