Repository sofastack/sofastack.tech, pull requests merged in 2020-03, with the labels that each got.

#427 Update contributors.
  content/zh/awesome/_index.md
Labels: cla:yes, size/M

#428 Fix markdown render errors
  content/en/projects/sofa-rpc/fault-hystrix/index.md
  content/zh/projects/sofa-rpc/fault-hystrix/index.md
Labels: cla:yes, kind/docs, proj/sofa-rpc, size/M

#429 Add a new blog
  content/zh/blog/sofa-registry-data-consistency/index.md
Labels: cla:yes, size/L

#430 Modify the blog
  content/zh/blog/sofa-registry-data-consistency/index.md
Labels: cla:yes, size/XS

#433 Add campus.
  content/zh/hr/campus/_index.md
Labels: cla:yes, size/M

#437 Update QR code of dingtalk group, contributors and end users.
  content/zh/awesome/_index.md
  static/img/qrcode/qrcode_2.png
Labels: cla:yes, size/M

#438 Modify a new blog
  content/zh/blog/sofa-channel-12-retrospect/index.md
Labels: cla:yes, size/L

#440 Modify a new blog
  content/zh/blog/sofa-weekly-20200313/index.md
Labels: cla:yes, size/L

#441 Update the blog
  content/zh/blog/sofa-ark-overview/index.md
Labels: cla:yes, size/XS

#442 Modify the activity
  content/zh/activities/sofa-channel-13/index.md
Labels: cla:yes, size/M

#446 Add a new blog
  content/zh/blog/sofa-ark-maven- packaging-plugins/index.md
Labels: cla:yes, size/L

#449 Update document of nacos support
  content/zh/projects/sofa-rpc/registry-nacos/index.md
Labels: cla:yes, size/XS

#450 Update table format
  content/zh/projects/sofa-dashboard/dashboard-client/index.md
Labels: cla:yes, size/S

#452 Add a new blog
  content/zh/blog/service-mesh-api-udpa-follow-up/index.md
Labels: cla:yes, size/L

#453 Modify the blog
  content/zh/blog/service-mesh-api-udpa-follow-up/index.md
Labels: cla:yes, size/XS

#454 Update the blog
  content/zh/blog/service-mesh-api-udpa-follow-up/index.md
Labels: cla:yes, size/XS

#457 Add a new blog
  content/zh/blog/sofa-weekly-0327/index.md
Labels: cla:yes, size/L

#458 Add a new activity
  content/zh/activities/sofa-channel-14/index.md
Labels: cla:yes, size/M

#459 Modify the activity
  content/zh/activities/sofa-channel-13/index.md
Labels: cla:yes, size/XS
