Repository sofastack/sofastack.tech, pull requests merged in 2020-12, with the labels that each got.

#593 Add a new file
  content/zh/blog/sofa-weekly-20201204/index.md
Labels: cla:yes, size/M

#594 Add a new file
  content/zh/blog/sofa-weekly-20201211/index.md
Labels: cla:yes, size/M

#596 Add a new file
  content/zh/blog/sofa-weekly-20201218/index.md
Labels: cla:yes, size/M

#597 Update config.yml
  .circleci/config.yml
Labels: cla:yes, size/S

#599 Fix typo
  content/zh/blog/sofa-ark-overview/index.md
  content/zh/projects/sofa-boot/sofa-ark-readme/index.md
Labels: First-time contributor, bug, cla:yes, size/XS

#600 Add a new file
  content/zh/blog/sofa-weekly-20201225/index.md
Labels: cla:yes, size/M

#601 Add a new file
  content/zh/blog/sofa-weekly-20201231/index.md
Labels: cla:yes, size/M
