Repository sofastack/sofastack.tech, pull requests merged in 2020-05, with the labels that each got.

#482 Add a new blog
  content/zh/blog/sofa-jraft-priority-election/index.md
Labels: cla:yes, size/L

#483 sofajraft 1.3.1 features
  content/zh/projects/sofa-jraft/release-log/index.md
Labels: cla:yes, size/S

#484 Add a new blog
  content/zh/blog/kata-container-introduction-to-safe-containers/index.md
Labels: cla:yes, size/L

#485 Add a new blog
  content/zh/blog/sofa-weekly-20200508/index.md
Labels: cla:yes, size/L

#490 Add a new blog
  content/zh/blog/mosn-transparent-hijacking/index.md
Labels: cla:yes, size/M

#491 Modify the blog
  content/zh/blog/mosn-transparent-hijacking/index.md
Labels: cla:yes, size/XS

#493 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/M

#494 Delete the blog
  content/zh/guides/sofastack-demos
Labels: cla:yes, size/S

#496 Add a new guide
  content/zh/guides/sofastack-demos/index.md
Labels: cla:yes, size/S

#497 Add a new blog
  content/zh/blog/sofa-channel-16-retrospect/index.md
Labels: cla:yes, size/L

#498 Add new guide
  content/zh/guides/_index.md
Labels: cla:yes, size/XS

#499 Modify the blog
  content/zh/blog/sofa-channel-16-retrospect/index.md
Labels: cla:yes, size/XS

#500 Add a new blog:sofa-weekly-20200522
  content/zh/blog/sofa-weekly-20200522/index.md
Labels: cla:yes, size/L

#503 Add a new blog
  content/zh/service-mesh-virtual-meetup1-skywalking-observability-applications/index.md
Labels: cla:yes, size/L

#504 Delete the blog
  content/zh/service-mesh-virtual-meetup1-skywalking-observability-applications/index.md
Labels: cla:yes, size/L

#505 Add a new blog
  content/zh/blog/service-mesh-virtual-meetup1-skywalking-observability-applications/index.md
Labels: cla:yes, size/L

#506 Add a new blog
  content/zh/blog/sofa-weekly-20200529
Labels: cla:yes, size/M

#508 Add a new blog
  content/zh/blog/sofa-weekly-20200529/index.md
Labels: cla:yes, size/M

#510 Modifty the blog
  content/zh/blog/sofa-weekly-20200529/index.md
Labels: cla:yes, size/XS
