Repository sofastack/sofastack.tech, pull requests merged in 2020-06, with the labels that each got.

#501 illustration update
  content/zh/projects/sofa-boot/parallel-start/module-parallel.png
Labels: First-time contributor, cla:no, size/XS

#511 A little modification for index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: First-time contributor, cla:no, size/XS

#512 Add a new blog
  content/zh/blog/service-mesh-virtual-meetup1-service-mesh-observability-practice/index.md
Labels: cla:yes, size/L

#513 Add a new blog
  content/zh/blog/service-mesh-webinar-duodian-istio-mosn-dubbo/index.md
Labels: cla:yes, size/L

#514 Add a new blog：weekly
  content/zh/blog/sofa-weekly-20200605/index.md
Labels: cla:yes, size/L

#515 Add a new blog
  content/zh/blog/mosn-dubbo-dubbo-go-hessian2-performance-optimization/index.md
Labels: cla:yes, size/L

#516 Modify the blog
  content/zh/blog/mosn-dubbo-dubbo-go-hessian2-performance-optimization/index.md
Labels: cla:yes, size/XS

#517 Add a new blog
  content/zh/blog/forrester-daipeng-white-paper-cloud-native/index.md
Labels: cla:yes, size/M

#518 Add a new blog
  content/zh/blog/sofa-weekly-20200612/index.md
Labels: cla:yes, size/M

#519 Modify the blog
  content/zh/blog/sofa-weekly-20200612/index.md
Labels: cla:yes, size/XS

#520 Add a new blog
  content/zh/blog/antfin-service-mesh-monitor-landing-experience/index.md
Labels: cla:yes, size/L

#521 Add a new blog
  content/zh/blog/service-mesh-the-road-ahead-long/index.md
Labels: cla:yes, size/L

#522 Add a new blog
  content/zh/blog/antfin-monitoring-cloud-native-observable-market-design-overview/index.md
Labels: cla:yes, size/L

#523 Add a new blog
  content/zh/blog/sofa-weekly-20200619/index.md
Labels: cla:yes, size/L

#525 sofajraft 1.3.2 features
  content/zh/projects/sofa-jraft/release-log/index.md
Labels: cla:yes, size/S

#527 Update index.md
  content/zh/projects/sofa-boot/sofa-ark-ark-plugin/index.md
Labels: First-time contributor, cla:no, size/XS

#528 Add a new blog
  content/zh/blog/twenty-years-of-image-format-from-Knoppix-to-OCI-Image-v2/index.md
Labels: cla:yes, size/L

#529 Update the image
  content/zh/blog/twenty-years-of-image-format-from-Knoppix-to-OCI-Image-v2/index.md
Labels: cla:yes, size/XS

#531 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#530 update reference with one missing property local-first
  content/en/projects/sofa-rpc/rpc-config-xml-explain/index.md
Labels: First-time contributor, cla:no, size/XS
