Repository sofastack/sofastack.tech, pull requests merged in 2020-11, with the labels that each got.

#581 Updata the blog
  content/zh/blog/seata-distributed-transaction-open-source/index.md
Labels: cla:yes, size/XS

#583 Add a new blog
  content/zh/blog/sofa-weekly-20201106/index.md
Labels: cla:yes, size/L

#584 Update contributors.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#585 Add a new blog
  content/zh/blog/sofa-weekly-20201113/index.md
Labels: First-time contributor, cla:no, size/M

#589 Add a new file
  content/zh/blog/sofa-weekly-20201120/index.md
Labels: cla:yes, size/M

#590 Update index.md
  content/zh/blog/sofa-weekly-20201120/index.md
Labels: cla:yes, size/XS

#591 Add a new file
  content/zh/blog/20201127/index.md
Labels: cla:yes, size/M

#582 fix configuration-fault-tolerance link description
  content/zh/projects/sofa-rpc/fault-tolerance/index.md
Labels: bug, cla:yes, size/XS

#587 [ISSUE-#586] Fix jraft user-guide index.md endpoint code demo
  content/en/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: First-time contributor, bug, cla:yes, size/S

#592 Update contributors and logo.
  content/zh/awesome/_index.md
  content/zh/blog/sofa-weekly-20201127/index.md
Labels: cla:yes, size/L
