Repository sofastack/sofastack.tech, pull requests merged in 2020-08, with the labels that each got.

#548 Add a new blog：sofa-weekly-20200731
  content/zh/blog/sofa-weekly-20200731/index.md
Labels: cla:yes, size/L

#549 Add a new blog
  content/zh/blog/kata-container-2.0-road-to-attack/index.md
Labels: cla:yes, size/M

#550 Add a new blog
  content/zh/blog/five-years-to-ali-p8/index.md
Labels: cla:yes, size/M

#551 Update index.md
  content/zh/projects/sofa-rpc/configuration-fault-tolerance/index.md
Labels: First-time contributor, cla:yes, size/XS

#552 Add a new blog
  content/zh/blog/sofa-weekly-20200807/index.md
Labels: cla:yes, size/L

#553 Add a new blog
  content/zh/blog/antgroup-sofastack-rivers-and-lakes-on-the-cloud/index.md
Labels: cla:yes, size/L

#554 Add a new blog
  content/zh/blog/antgroup-k8s-security-protection-of-cluster-sensitive-information/index.md
Labels: cla:yes, size/M

#555 Add a new blog
  content/zh/blog/sofa-weekly-20200814/index.md
Labels: cla:yes, size/L

#558 Add a new blog
  content/zh/blog/antgroup-kubernetes-high-slo/index.md
Labels: cla:yes, size/M

#559 Update the blog
  content/zh/blog/antgroup-kubernetes-high-slo/index.md
Labels: cla:yes, size/XS

#563 Add a new blog：sofa-weekly
  content/zh/blog/sofa-weekly-20200828/index.md
Labels: cla:yes, size/M
