Repository sofastack/sofastack.tech, pull requests merged in 2020-04, with the labels that each got.

#460 Add a new blog
  content/zh/blog/sofa-weekly-20200403/index.md
Labels: cla:yes, size/L

#461 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#462 Modify the blog
  content/zh/blog/sofa-weekly-20200403/index.md
Labels: cla:yes, size/XS

#463 Add a new blog
  content/zh/blosofa-registry-dataserver-smooth-expansion-contraction/index.md
Labels: cla:yes, size/L

#464 Add a new blog
  content/zh/blog/sofa-registry-dataserver-smooth-expansion-contraction/index.md
Labels: cla:yes, size/XS

#465 Update a link in footer
  data/en/home.toml
  data/zh/home.toml
  layouts/partials/footer.html
Labels: cla:yes, size/S

#466 Add a new blog
  content/zh/blog/sofa-channel-14-retrospect/index.md
Labels: cla:yes, size/L

#467 Add a new blog
  content/zh/blog/sofa-weekly-20200410/index.md
Labels: cla:yes, size/L

#468 Add a new blog
  content/zh/blog/sofa-weekly-20200417/index.md
Labels: cla:yes, size/M

#469 upgrade ark doc
  content/zh/projects/sofa-boot/sofa-ark-ark-event/index.md
  content/zh/projects/sofa-boot/sofa-ark-ark-extension/index.md
Labels: size/L

#470 Add a new activity
  content/zh/activities/sofa-channel-15
Labels: cla:yes, size/M

#471 Delete the activity
  content/zh/activities/sofa-channel-15
Labels: cla:yes, size/M

#472 Add a new activity
  content/zh/activities/sofa-channel-15/index.md
Labels: cla:yes, size/M

#473 Modify the activity
  content/zh/activities/sofa-channel-15/index.md
Labels: cla:yes, size/XS

#474 Modify the blog
  content/zh/activities/sofa-channel-14/index.md
Labels: cla:yes, size/XS

#475 Add a new blog：sofa-weekly-20200424
  content/zh/blog/sofa-weekly-20200424/index.md
Labels: cla:yes, size/M

#476 Add a new blog
  content/zh/blog/sofa-channel-15-retrospect/index.md
Labels: cla:yes, size/L

#477 Update SOFAMesh's description
  content/en/projects/sofa-mesh/overview/index.md
  content/zh/projects/sofa-mesh/overview/index.md
Labels: cla:yes, size/S

#478 Add a new blog
  content/zh/blog/service-mesh-api-gateway-in-depth-discussion-of-relationships/index.md
Labels: cla:yes, size/L

#479 Modify the blog
  content/zh/blog/service-mesh-api-gateway-in-depth-discussion-of-relationships/index.md
Labels: cla:yes, size/XS

#480 Add a new acticity
  content/zh/activities/sofa-channel-16/index.md
Labels: cla:yes, size/M
