Repository sofastack/sofastack.tech, pull requests merged in 2021-05, with the labels that each got.

#648 Update index.md
  content/zh/activities/sofa-meetup-5/index.md
Labels: cla:yes, size/S

#650 SOFA Weekly |QA 整理
  content/zh/blog/index.md
Labels: cla:yes, size/M

#649 add the missing punctuation and change the meaning
  content/zh/projects/sofa-jraft/how-to-contribute-code-to-sofajraft/index.md
Labels: cla:yes, size/S

#651 Revert "SOFA Weekly |QA 整理"
  content/zh/blog/index.md
Labels: cla:yes, size/M

#652 Add a new file
  content/zh/blog/sofa-weekly-20210507/index.md
Labels: cla:yes, size/M

#653 Add a new file
  content/zh/activities/sofa-meetup-6/index.md
Labels: cla:yes, size/L

#654 Add a new file
  content/zh/activities/sofa-channel-20/index.md
Labels: cla:yes, size/M

#655 Some tune about jraft.
  content/en/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, size/M

#656 Update index.md
  content/zh/activities/sofa-meetup-6/index.md
Labels: cla:yes, size/XS

#658 Create index.md
  content/zh/blog/sofa-weekly-20210514/index.md
Labels: First-time contributor, cla:yes, size/M

#659 Add a new file
  content/zh/blog/20210521/index.md
Labels: cla:yes, size/M

#660 Create index.md
  content/zh/activities/sofa-channel-20/index.md
Labels: cla:yes, size/XS

#661 Update index.md
  content/zh/activities/sofa-meetup-6/index.md
Labels: cla:yes, size/XS

#662 Update index.md
  content/zh/blog/20210521/index.md
Labels: cla:yes, size/XS

#664 Create index.md
  content/zh/activities/Summer 2021 of Open Source Promotion Plan/index.md
Labels: cla:yes, size/M

#666 Create index.md
  content/zh/blog/Exploration and Practice of AntCloud Native Application Runtime - ArchSummit Shanghai/index.md
Labels: cla:yes, size/L

#667 Update index.md
  content/zh/activities/Summer 2021 of Open Source Promotion Plan/index.md
Labels: cla:yes, size/XS

#668 Create index.md
  content/zh/blog/sofa-weekly-20200528/index.md
Labels: cla:yes, size/M
