Repository sofastack/sofastack.tech, pull requests merged in 2021-11, with the labels that each got.

#772 Delete content/zh/activities/sofa-meetup-11 directory
  content/zh/activities/sofa-meetup-11/index.md
Labels: cla:yes, size/M

#771 Create index.md
  content/zh/blog/how-to-troubleshoot-high-rust-memory-usage-in-a-production-environment/index.md
Labels: size/L, cla:yes

#773 Update index.md
  content/zh/activities/sofa-meetup-12/index.md
Labels: cla:yes, size/XS

#774 Create index.md
  content/zh/blog/sofa-weekly-20211105/index.md
Labels: size/L, cla:yes

#776 Update index.md
  content/zh/blog/how-to-troubleshoot-high-rust-memory-usage-in-a-production-environment/index.md
Labels: cla:yes, size/XS

#775 Create sofa-weekly-20211029
  content/zh/blog/sofa-weekly-20211029-1/index.md
Labels: size/L, cla:yes

#777 Create index.md
  content/zh/blog/what-exactly-is-the-overwhelming-cloud-native/index.md
Labels: size/L, cla:yes

#778 Create index.md
  content/zh/activities/sofa-channel-22/index.md
Labels: cla:yes, size/M

#779 Create index.md
  content/zh/blog/sofa-weekly-20211112/index.md
Labels: size/L, cla:yes

#780 Create index.md
  content/zh/prometheus-on-ceresdb-evolutionary-path/index.md
Labels: size/L, cla:yes

#781 Create index.md
  content/zh/blog/sofa-weekly-20211119/index.md
Labels: size/L, cla:yes

#782 Create index.md
  content/zh/blog/reduce-costs-and-improve-efficiency-the-metamorphosis-of-the-registration-centre-at-ant-group/index.md
Labels: size/L, cla:yes

#783 add rejectedExecutionPolicy config description
  content/zh/projects/sofa-rpc/configuration-common/index.md
Labels: cla:yes, size/XS

#784 add rejectedExecutionPolicy config description
  content/en/projects/sofa-rpc/configuration-common/index.md
Labels: cla:yes, size/XS

#785 Create index.md
  content/zh/blog/sofa-weekly-20211126/index.md
Labels: size/L, cla:yes

#786 Delete index.md
  content/zh/blog/what-exactly-is-the-overwhelming-cloud-native/index.md
Labels: size/L, cla:yes
