Repository sofastack/sofastack.tech, pull requests merged in 2021-06, with the labels that each got.

#670 Create index.md
  content/zh/blog/Protecting Critical Operations with Secure Computing/index.md
Labels: cla:yes, size/L

#669 Create index.md
  content/zh/blog/Helping data security: Ant and Intel work together to create a verified PPML solution/index.md
Labels: cla:yes, size/M

#673 Create index.md
  content/zh/blog/sofa-weekly-20210604/index.md
Labels: cla:yes, size/M

#674 Create index.md
  content/zh/blog/the-secret-of-anolisos/index.md
Labels: cla:yes, size/L

#675 Create index.md
  content/zh/activities/sofa-meetup-7/index.md
Labels: cla:yes, size/M

#676 Create index.md
  content/zh/blog/sofa-weekly-0611/index.md
Labels: cla:yes, size/M

#677 Create index.md
  content/zh/blog/gopher-china-2021-interview-with-song-shun-the-application-and-practice-of-go-in-ant-group/index.md
Labels: cla:yes, size/M

#680 Create index.md
  content/zh/blog/sofa-weekly-20210618/index.md
Labels: cla:yes, size/M

#681 Create index.md
  content/zh/blog/mosn-subproject-layotto-opening-a-new-chapter-in-service-grid-application-runtime/index.md
Labels: cla:yes, size/L

#678 Update index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, size/XS
