Repository sofastack/sofastack.tech, pull requests merged in 2021-01, with the labels that each got.

#603 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#604 Add a new file
  content/zh/blog/sofa-weekly-20210108/index.md
Labels: cla:yes, size/M

#605 Update index.md
  content/en/projects/sofa-boot/quick-start/index.md
  content/zh/projects/sofa-boot/quick-start/index.md
Labels: First-time contributor, cla:yes, size/S

#602 Updata the blog
  content/zh/projects/sofa-jraft/counter-example/index.md
Labels: cla:yes, size/XS

#606 Add a new file
  content/zh/blog/sofa-weekly-20210115/index.md
Labels: cla:yes, size/M

#608 Update contributors and end users.
  content/zh/awesome/_index.md
Labels: cla:yes, size/L

#609 Add a new file
  content/zh/blog/20210122/index.md
Labels: First-time contributor, cla:yes, size/M

#610 Change year to 2021.
  content/zh/hr/campus/_index.md
  layouts/partials/footer.html
Labels: cla:yes, size/XS
