Repository sofastack/sofastack.tech, pull requests merged in 2021-08, with the labels that each got.

#699 Create index.md
  content/zh/blog/sofa-weekly-20210730/index.md
Labels: cla:yes, size/L

#698 Create index.md
  内容/zh/博客/ant-groups-10000-scale-k8s-cluster-etcd-high-availability-construction-road/index.md
Labels: cla:yes, size/L

#700 Create index.md
  content/zh/blog/kcl-a-declarative-cloud-native-configuration-policy-language/index.md
Labels: cla:yes, size/L

#697 Update index.md
  content/zh/activities/sofa-meetup-9/index.md
Labels: cla:yes, size/XS

#707 Create index.md
  content/zh/blog/ant-group-sofatracer-principles-and-practices/index.md
Labels: size/L, cla:yes

#706 Create sofa-channel-21
  content/zh/activities/sofa-channel-21/index.md
Labels: cla:yes, size/M

#704 Modify the description of failover summary in rheakv
  content/en/projects/sofa-jraft/jraft-rheakv-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-rheakv-user-guide/index.md
Labels: cla:yes

#701 Add cancel tc command.
  content/en/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, size/S

#708 Create index.md
  content/zh/blog/sofa-weekly-20210813/index.md
Labels: size/L, cla:yes

#710 Create index.md
  content/zh/2021-cloud-native-technology-development-status-and-future-trends/index.md
Labels: size/L, cla:yes

#711 Create index.md
  content/zh/activities/sofa-channel-21-1/index.md
Labels: cla:yes, size/M

#712 Create index.md
  content/zh/blog/sofa-weekly-20210820/index.md
Labels: size/L, cla:yes

#714 Update index.md
  content/zh/activities/sofa-meetup-8/index.md
Labels: cla:yes, size/XS

#715 Create index.md
  content/zh/activities/sofa-meetup-10/index.md
Labels: cla:yes, size/M
