Repository sofastack/sofastack.tech, pull requests merged in 2021-09, with the labels that each got.

#716 Create index.md
  content/zh/blog/sofa-star-is-recruiting/index.md
Labels: cla:yes, size/M

#719 Create index.md
  content/zh/blog/ant-intelligent-monitoring/index.md
Labels: size/L, cla:yes

#720 Up-to-date metrics docs.
  content/en/projects/sofa-jraft/jraft-user-guide/index.md
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: size/L, cla:yes

#723 fix format.
  content/en/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, size/XS, bug

#721 Update index.md
  content/zh/activities/sofa-meetup-10/index.md
Labels: size/L, cla:yes

#724 Update index.md
  content/zh/activities/sofa-meetup-10/index.md
Labels: cla:yes, size/XS

#725 Update index.md
  content/zh/blog/sofa-weekly-20210723/index.md
Labels: cla:yes, size/XS

#726 Update index.md
  content/zh/activities/sofa-meetup-10/index.md
Labels: cla:yes, size/XS

#728 Create index.md
  content/zh/blog/sofa-weekly-20210806/index.md
Labels: cla:yes, size/M

#732 Delete content/zh/activities/sofa-meetup-9 directory
  content/zh/activities/sofa-meetup-9/index.md
Labels: size/L, cla:yes

#733 Delete content/zh/activities/sofa-channel-21 directory
  content/zh/activities/sofa-channel-21/index.md
Labels: cla:yes, size/M

#731 Create index.md
  content/zh/blog/restricted-flow-on-the-technology-windfall/index.md
Labels: size/L, cla:yes

#729 Create index.md
  content/zh/blog/sofa-weekly-00903inde/index.md
Labels: size/L, cla:yes

#730 Create index.md
  content/zh/blog/sofa-weekly-00910/index.md
Labels: cla:yes, size/M

#727 Create index.md
  content/zh/blog/sofa-weekly-20210917/index.md
Labels: size/L, cla:yes

#738 Create index.md
  content/zh/blog/sofajraft-in-practice-in-the-same-tour/index.md
Labels: size/L, cla:yes

#749 Update index.md
  content/zh/blog/restricted-flow-on-the-technology-windfall/index.md
Labels: cla:yes, size/M

#748 Update index.md
  content/zh/blog/sofa-weekly-20210917/index.md
Labels: cla:yes, size/S

#747 Rename content/zh/blog/sofa-weekly-00910/index.md to content/zh/blog/…
  content/zh/blog/sofa-weekly-20210910/index.md
Labels: cla:yes, size/XS

#739 fix: 修复“Ark Plugin 存在四个概念”下的第一项没有正确显示的bug
  content/zh/projects/sofa-boot/sofa-ark-ark-plugin-demo/index.md
Labels: cla:no, cla:yes, size/XS, bug, First-time contributor

#751 Create index.md
  content/zh/blog/sofa-weekly-20210924/index.md
Labels: cla:yes, size/M

#752 Update index.md
  content/zh/blog/sofajraft-in-practice-in-the-same-tour/index.md
Labels: cla:yes, size/M

#753 Update and rename content/zh/blog/sofa-weekly-00903inde/index.md to c…
  content/zh/blog/sofa-weekly-20210903/index.md
Labels: cla:yes, size/M

#758 Update index.md
  content/zh/blog/sofa-weekly-20210910/index.md
Labels: cla:yes, size/S

#757 Update index.md
  content/zh/blog/sofajraft-in-practice-in-the-same-tour/index.md
Labels: size/L, cla:yes

#756 Create index.md
  content/zh/blog/climbing-to-the-top-of-scale-ant-groups-large-scale-sigma-cluster-apiserver-optimization-in-practice/index.md
Labels: size/L, cla:yes
