Repository sofastack/sofastack.tech, pull requests merged in 2021-12, with the labels that each got.

#790 Create index.md
  content/zh/blog/sofa-weekly-20211203/index.md
Labels: size/L, cla:yes

#789 Create index.md
  content/zh/blog/prometheus-on-ceresdb-evolutionary-path/index.md
Labels: size/L, cla:yes

#788 Update and rename content/zh/blog/sofa-weekly-20211029-1/index.md to …
  content/zh/blog/sofa-weekly-20211029/index.md
Labels: cla:yes, size/XS

#787 Update index.md
  content/zh/blog/sofa-weekly-20211105/index.md
Labels: cla:yes, size/XS

#791 Create index.md
  content/zh/blog/the-next-five-years-of-cloud-native-runtime/index.md
Labels: size/L, cla:yes

#792 Update index.md
  content/zh/blog/sofa-weekly-20211029/index.md
Labels: cla:yes, size/XS

#793 Update index.md
  content/zh/blog/how-to-troubleshoot-high-rust-memory-usage-in-a-production-environment/index.md
Labels: cla:yes, size/XS

#794 修正Ark Biz简介部分 execution 单词拼写错误
  content/zh/projects/sofa-boot/sofa-ark-ark-biz/index.md
Labels: cla:no, size/XS, First-time contributor

#795 Create index.md
  content/zh/activities/sofa-channel-23/index.md
Labels: cla:yes, size/M

#797 Create index.md
  content/zh/blog/sofa-weekly-20211210/index.md
Labels: size/L, cla:yes

#796 Create index.md
  content/zh/blog/exploration-and-practice-of-service-mesh-in-icbc/index.md
Labels: size/L, cla:yes

#798 Create index.md
  content/zh/blog/online-business-double-eleven-servicemesh-technology-based-service-link-isolation-technology-and-practice/index.md
Labels: size/L, cla:yes

#799 sofaregistry v6
  content/en/projects/sofa-registry/deployment/index.md
  content/en/projects/sofa-registry/server-quick-start/index.md
  content/zh/projects/sofa-registry/deployment/index.md
  content/zh/projects/sofa-registry/management-api/index.md
  content/zh/projects/sofa-registry/server-quick-start/index.md
Labels: cla:yes, size/XL

#800 Create index.md
  content/zh/blog/sofa-weekly-20211217/index.md
Labels: size/L, cla:yes

#801 Create index.md
  content/zh/activities/sofa-meetup-13/index.md
Labels: size/L, cla:yes

#803 Create index.md
  content/zh/blog/deeper-into-http/3-evolution-of-the-protocol-from-the-creation-and-closing-of-quic-links/index.md
Labels: size/L, cla:yes

#804 Create index.md
  content/zh/blog/the-practice-and-thinking-behind-sofastack/index.md
Labels: cla:yes, size/M

#805 Create index.md
  content/zh/blog/sofa-weekly-20211224/index.md
Labels: size/L, cla:yes

#806 Create index.md
  content/zh/blog/one-line-of-code-to-reduce-carbon-emissions-by-100000kg/index.md
Labels: size/L, cla:yes

#807 sofa-registry IDEA quick start
  content/en/projects/sofa-registry/server-quick-start/index.md
  content/zh/projects/sofa-registry/server-quick-start/index.md
Labels: cla:yes, size/S

#808 Create index.md
  content/zh/blog/sofa-weekly-20211231/index.md
Labels: size/L, cla:yes
