Repository sofastack/sofastack.tech, pull requests merged in 2021-03, with the labels that each got.

#622 Add a new file
  content/zh/blog/sofa-weekly-20210212/index.md
Labels: cla:yes, size/M

#619 Add service mesh
  content/zh/blog/service-mesh-exploration-thinking-after-1111-1/index.md
Labels: First-time contributor, cla:yes, size/L

#621 Add Serverless Task Doc
  content/zh/blog/antgroup-serverless-task/index.md
Labels: cla:yes, size/M

#623 Add a new file
  content/zh/blog/sofa-weekly-20210305/index.md
Labels: cla:yes, size/M

#624 Add a new file
  content/zh/activities/sofa-meetup-4/index.md
Labels: cla:yes, size/L

#626 Add a new file
  content/zh/blog/sofa-weekly-20210312/index.md
Labels: cla:yes, size/M

#627 Add a new file
  content/zh/blog/sofa-weekly-20210319/index.md
Labels: cla:yes, size/M

#628 Update README.md
  README.md
Labels: cla:yes, size/XS

#630 Update index.md
  content/zh/projects/sofa-rpc/getting-started-with-sofa-boot/index.md
Labels: cla:yes, size/XS

#629 Update index.md
  content/zh/activities/sofa-meetup-4/index.md
Labels: cla:yes, size/XS

#631 add mosn-meetup-4-deploy-automation-at-large-scale
  content/zh/blog/mosn-meetup-4-deploy-automation-at-large-scale/index.md
Labels: First-time contributor, cla:yes, size/M

#633 Add a new file
  content/zh/blog/sofa-weekly-20210326/index.md
Labels: cla:yes, size/M
