Repository sofastack/sofastack.tech, pull requests merged in 2021-02, with the labels that each got.

#613 Add files via upload
  static/img/qrcode/qrcode_2.png
Labels: cla:yes, size/XS

#612 Add a new file
  内容/zh/博客/沙发每周20210129/index.md
Labels: cla:yes, size/M

#615 Update qrcode of dingtalk.
  static/img/qrcode/qrcode_2.png
Labels: cla:yes, size/XS

#617 Add a new file
  content/zh/blog/sofa-weekly-20210205/index.md
Labels: cla:yes, size/L

#618 Add a new file
  content/zh/blog/sofa-weekly-20210219/index.md
Labels: cla:yes, size/M

#620 Add a new file
  content/zh/blog/sofa-weekly20210226/index.md
Labels: cla:yes, size/M
