Repository sofastack/sofastack.tech, pull requests merged in 2021-04, with the labels that each got.

#634 Add a new file
  content/zh/blog/sofa-weekly-20210402/index.md
Labels: cla:yes, size/M

#635 ACreate index.md
  content/zh/blog/sofa-weekly-20210409/index.md
Labels: cla:yes, size/M

#637 Create index.md
  content/zh/blog/sofa-weekly-20210409/index.md
  content/zh/blog/sofa-weekly-20210416/index.md
Labels: cla:yes, size/M

#642 sofaboot config example
  content/zh/projects/sofa-rpc/application-rpc-config/index.md
Labels: First-time contributor, cla:yes, size/L

#643 modify typos
  content/zh/projects/sofa-jraft/raft-introduction/index.md
Labels: First-time contributor, cla:no, size/XS

#645 Add a new file
  content/zh/blog/sofa-weekly-20210423/index.md
Labels: cla:yes, size/M

#646 Update index.md
  content/zh/blog/sofa-weekly-20210423/index.md
Labels: cla:yes, size/XS

#632 sofagw
  content/zh/blog/sofagw-cross-domain-communication-solution/index.md
Labels: First-time contributor, cla:yes, size/L

#647 Add a new
  content/zh/blog/sofa-weekly-0430/index.md
Labels: cla:yes, size/M
