Repository sofastack/sofastack.tech, pull requests merged in 2022-04, with the labels that each got.

#874 Create index.md
  content/zh/blog/sofa-weekly-20220401/index.md
Labels: size/L, cla:yes

#875 Create index.md
  content/zh/blog/exploratory-practice-of-heterogeneous-registration-centre-mechanism-in-icbc/index.md
Labels: size/L, cla:yes

#873 Create index.md
  content/zh/activities/sofa-meetup-14/index.md
Labels: size/L, cla:yes

#879 Create index.md
  community-article-mosn-community-performance-analysis-tool-holmes-principle-analysis/index.md
Labels: size/L, cla:yes

#880 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-communication-data-compression/index.md
Labels: cla:yes, size/M

#881 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#882 Update index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-communication-data-compression/index.md
Labels: cla:yes, size/XS

#883 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-data-synchronization/index.md
Labels: size/L, cla:yes

#884 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#885 Create index.md
  content/zh/blog/sofa-weekly-20220408/index.md
Labels: size/L, cla:yes

#886 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-slottable/index.md
Labels: cla:yes, size/XL

#887 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#889 Create index.md
  content/zh/activities/sofastack-four-years-of-open-source/index.md
Labels: cla:yes, size/M

#890 sofa-ark-migration-guide
  content/zh/projects/sofa-boot/_index.md
  content/zh/projects/sofa-boot/sofa-ark-migration-guide/index.md
Labels: size/L, cla:yes, First-time contributor

#891 Create sofa-weekly-20220422
  content/zh/blog/sofa-weekly-20210422/index.md
Labels: size/L, cla:yes

#892 Create index.md
  content/zh/blog/mosn-1-0-released-starting-a-new-architectural-evolution/index.md
Labels: size/L, cla:yes
