Repository sofastack/sofastack.tech, pull requests merged in 2022-11, with the labels that each got.

#1038 Create index.md
  content/zh/blog/sofaregistry-large-scale-cluster-optimization-practice/20221103/index.md
Labels: cla:yes, size/XL

#1049 Update index.md
  content/zh/activities/sofa-channel-29/index.md
Labels: cla:yes, size/S

#1050 Create index.md
  content/zh/activities/sofa-channel-30/index.md
Labels: cla:yes, size/M

#1065 Create index.md
  content/p2p-transfer-protocol-optimization-in-dragonfly/index.md
Labels: size/L, cla:yes

#1067 Create index.md
  content/zh/blog/sofa-weekly-20221122/index.md
Labels: cla:yes, size/M

#1066 Create index.md
  content/zh/blog/p2p-transfer-protocol-optimization-in-dragonfly/index.md
Labels: size/L, cla:yes

#1068 Create index.md
  content/zh/blog/container-image-basics/index.md
Labels: cla:yes, size/XL

#1069 Create index.md
  content/zh/blog/sofa-weekly-20221104/index.md
Labels: cla:yes, size/M

#1072 Create index.md
  content/zh/blog/tongsuo-supports-the-semi-homomorphic-encryption-algorithm-paillier/index.md
Labels: size/L, cla:yes

#1074 Create index.md
  content/zh/blog/is-sidecarless-the-next-stop-for-servicemesh/index.md
Labels: size/L, cla:yes
