Repository sofastack/sofastack.tech, pull requests merged in 2022-12, with the labels that each got.

#1077 Create index.md
  content/zh/blog/cost-reduction-and-efficiency-increase-ants-exploration-and-practice-in-sidecarless/index.md
Labels: size/L, cla:yes

#1078 Create index.md
  content/zh/blog/sofa-weekly-20221216/index.md
Labels: cla:yes, size/M

#1079 Create sofa-channel-31
  content/zh/activities/sofa-channel-31
Labels: cla:yes, size/M

#1082 Create index.md
  content/zh/blog/dragonfly-and-nydus-mirror-mode-integration-practice/index.md
Labels: cla:yes

#1080 Create index.md
  content/zh/blog/we-have-come-to-the-post-cloud-native-era-how-can-we-operate-and-maintain-on-a-large-scale/index.md
Labels: size/L, cla:yes

#1083 新增'Spring Boot 应用如何结合 SofaArk'
  content/zh/projects/sofa-boot/_index.md
  content/zh/projects/sofa-boot/sofa-ark-spring-boot-demo/index.md
Labels: size/L, cla:yes, First-time contributor
