Repository sofastack/sofastack.tech, pull requests merged in 2022-06, with the labels that each got.

#925 Create index.md
  content/zh/blog/how-to-think-about-multiple-runtime-architectures-like-dapr-layotto/index.md
Labels: size/L, cla:yes

#929 Create index.md
  content/zh/blog/the-two-years-that-broke-the-kusionstack-open-source-dilemma/index.md
Labels: size/L, cla:no, First-time contributor

#935 Update index.md
  content/zh/blog/deeperinto-http-3-2-the-not-so-boring-ssl/index.md
Labels: cla:yes, size/XS

#934 Update index.md
  content/zh/blog/sofa-weekly-20220527/index.md
Labels: cla:yes, size/XS

#933 Update index.md
  content/zh/blog/sofa-weekly-20220311/index.md
Labels: cla:yes, size/XS

#932 Update index.md
  content/zh/activities/sofa-channel-27/index.md
Labels: cla:yes, size/XS

#940 Update index.md
  content/zh/blog/sofa-weekly-20211119/index.md
Labels: cla:yes, size/XS

#938 Update index.md
  content/zh/blog/sofa-weekly-20211203/index.md
Labels: cla:yes, size/XS

#937 Update index.md
  content/zh/blog/2021sale-antmonitor-roundup-cloud-native-prometheus-monitoring-in-practice/index.md
Labels: cla:yes, size/XS

#948 Create index.md
  content/zh/projects/sofa-boot/overview/sofaboot-healthcheck-mechanism-explained/index.md
Labels: size/L, cla:yes

#949 修复源码解析健康检查描述
  content/zh/projects/sofa-boot/sofaboot-healthcheck-mechanism-explained/index.md
Labels: cla:yes, size/XS

#950 Update index.md
  content/zh/projects/sofa-boot/sofaboot-healthcheck-mechanism-explained/index.md
Labels: cla:yes, size/XS

#955 Update footer.html
  layouts/partials/footer.html
Labels: cla:yes, size/XS

#958 补充 SOFAArk 源码解析活动文章
  content/zh/projects/sofa-ark/_index.md
  content/zh/projects/sofa-boot/_index.md
  content/zh/projects/sofa-boot/sofa-ark-benchmark/index.md
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/debug-maven-plugin.png
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/header.png
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/index.md
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/plugin-execution-process.png
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/plugin-pakcages.png
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/sofaark-startup-process.png
  content/zh/projects/sofa-boot/sofa-ark-build-package-plugin/sofaboot-startup-process.png
  content/zh/projects/sofa-boot/sofa-ark-class-loader-delegation/index.md
  content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/index.md
  content/zh/projects/sofa-boot/sofa-ark-multi-web-component-deploy/index.md
  content/zh/projects/sofa-boot/sofa-ark-startup-process/index.md
Labels: size/L, cla:yes, First-time contributor

#959 Create index.md
  content/zh/blog/sofa-weekly-20220617/index.md
Labels: cla:yes, size/M

#961 添加源码解析部分
  content/zh/projects/sofa-boot/_index.md
Labels: cla:yes, size/XS

#960 Update index.md
  content/zh/projects/sofa-boot/sofa-ark-multi-web-component-deploy/index.md
Labels: size/L, cla:yes

#964 Create index.md
  content/zh/blog/sofa-weekly-20220624/index.md
Labels: cla:yes, size/M
