Repository sofastack/sofastack.tech, pull requests merged in 2022-03, with the labels that each got.

#836 Create index.md
  content/zh/blog/community-meeting-mosn-community-will-release-version-1-0-and-drive-the-next-generation-architecture-evolution/index.md
Labels: cla:yes, size/M

#837 Create index.md
  content/zh/blog/explore-sofaregistry-1-infrastructure/index.md
Labels: size/L, cla:yes

#838 Create index.md
  content/zh/blog/babassl-released-8-3-0-implementation-of-the-corresponding-privacy-computing-requirements/index.md
Labels: size/L, cla:yes

#839 Create index.md
  content/zh/blog/occlum-named-to-2021-sci-tech-china-open-source-innovation-list/index.md
Labels: cla:yes, size/M

#840 Create index.md
  content/zh/blog/sofa-weekly-20220304/index.md
Labels: size/L, cla:yes

#843 Create index.md
  babassl-support-for-semi-homomorphic-encryption-algorithm-ec-elgamal/index.md
Labels: size/L, cla:yes

#845 Update qrcode
  static/img/qrcode/qrcode_2.png
Labels: cla:yes, size/XS

#846 add local development
  content/en/projects/sofa-registry/server-quick-start/index.md
  content/zh/projects/sofa-registry/server-quick-start/index.md
Labels: cla:yes, size/S

#848 Create index.md
  content/zh/blog/sofa-weekly-20220311/index.md
Labels: cla:yes, size/M

#849 Create index.md
  content/zh/blog/community-article-mosn-routing-framework-explained/index.md
Labels: size/L, cla:yes

#850 [SOFARegistry] code-analyze directory
  content/en/projects/sofa-registry/_index.md
  content/en/projects/sofa-registry/code-analyze/summary/index.md
  content/zh/projects/sofa-registry/_index.md
  content/zh/projects/sofa-registry/code-analyze/summary/index.md
Labels: cla:yes, size/S

#851 Revert "[SOFARegistry] code-analyze directory"
  content/en/projects/sofa-registry/_index.md
  content/en/projects/sofa-registry/code-analyze/summary/index.md
  content/zh/projects/sofa-registry/_index.md
  content/zh/projects/sofa-registry/code-analyze/summary/index.md
Labels: cla:yes, size/S

#852 [SOFARegistry] code-analyze directory
  content/zh/projects/sofa-registry/_index.md
  content/zh/projects/sofa-registry/code-analyze/summary/index.md
  layouts/partials/post/meta/project_meta.html
Labels: cla:yes, size/S

#853 增加 jraft 1.3.10 关于反压策略的说明
  content/zh/projects/sofa-jraft/jraft-user-guide/index.md
Labels: cla:yes, size/S

#854 Create index.md
  content/zh/blog/sofaark-committer-interview-if-you-dont-like-it-just-change-it/index.md
Labels: size/L, cla:yes

#859 Create index.md
  content/zh/activities/sofa-channel-26/index.md
Labels: cla:yes, size/M

#858 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyza-data-table-listening/index.md
Labels: size/L, cla:yes

#861 Create index.md
  content/zh/blog/sofa-weekly-20220318/index.md
Labels: size/L, cla:yes

#862 源码解析目录
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#832 doc: update community governance rules
  content/zh/community/_index.md
Labels: size/L, cla:yes

#863 Create index.md
  content/zh/blog/nydus-mirror-acceleration-plugin-moves-to-containerd/index.md
Labels: size/L, cla:yes

#864 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-data-inverted-index/index.md
Labels: size/L, cla:yes

#865 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#866 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#867 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-push-delay-trace/index.md
Labels: size/L, cla:yes

#868 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#870 fixing typos
  content/zh/projects/sofa-jraft/raft-introduction/index.md
Labels: cla:yes, size/XS, First-time contributor

#871 Create index.md
  exploratory-practice-of-heterogeneous-registration-centre-mechanism-in-icbc/index.md
Labels: size/L, cla:yes

#872 Create index.md
  content/zh/blog/sofa-weekly-20220329/index.md
Labels: size/L, cla:yes
