Repository sofastack/sofastack.tech, pull requests merged in 2022-08, with the labels that each got.

#981 fix sofa-registry packaging command error
  content/zh/projects/sofa-registry/server-quick-start/index.md
Labels: cla:no, size/XS, bug, First-time contributor

#987 Create index.md
  content/zh/blog/mosn-reverse-channel-explained/index.md
Labels: size/L, cla:yes

#986 Create index.md
  content/zh/projects/sofa-boot/sofa-boot-context-isolation-mechanism-explained/index.md
Labels: cla:yes, size/XS

#989 Create index.md
  content/zh/blog/sofa-weekly-20220805/index.md
Labels: cla:yes, size/M

#990 Create sofa-meetup-9
  content/zh/activities/sofa-meetup-16/index.md
Labels: cla:yes, size/M

#991 Create index.md
  content/zh/activities/sofa-meetup-17/index.md
Labels: cla:yes, size/M

#992 Update index.md
  content/zh/activities/sofa-meetup-16/index.md
Labels: cla:yes, size/XS

#993 Update index.md
  content/zh/activities/sofa-meetup-17/index.md
Labels: cla:yes, size/XS

#970 SOFAArk 动态部署源码解析
  content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/index.md
  content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/install.png
  content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/lifecycle.png
Labels: cla:yes, First-time contributor, size/XL

#994 Update index.md
  content/zh/activities/sofa-meetup-17/index.md
Labels: cla:yes, size/XS

#995 Create index.md
  content/zh/blog/sofa-weekly-20220812/index.md
Labels: cla:yes, size/M

#996 Update index.md
  content/zh/activities/sofa-meetup-17/index.md
Labels: cla:yes, size/S

#998 Update index.md
  content/zh/projects/sofa-jraft/overview/index.md
Labels: cla:yes, size/XS

#997 Update _index.md
  content/zh/community/_index.md
Labels: cla:yes, size/XS

#1000 Update _index.md
  content/zh/awesome/_index.md
Labels: cla:yes, size/XS

#999 Update _index.md
  content/zh/community/_index.md
Labels: cla:yes, size/XS

#1001 Update index.md
  content/zh/activities/sofa-meetup-16/index.md
Labels: cla:yes, size/M

#1002 Update index.md
  content/zh/activities/sofa-meetup-17/index.md
Labels: cla:yes, size/S

#1003 Create index.md
  content/zh/blog/seata-php-semi-annual-planning/index.md
Labels: size/L, cla:yes

#1004 Update index.md
  content/zh/blog/mosn-reverse-channel-explained/index.md
Labels: cla:yes, size/XS

#1005 Update index.md
  content/zh/blog/seata-php-semi-annual-planning/index.md
Labels: cla:yes, size/M

#1006 Create index.md
  content/zh/activities/2022-IOSF/index.md
Labels: cla:yes, size/S

#1007 Create index.md
  content/zh/blog/sofa-weekly-20220819/index.md
Labels: cla:yes, size/M

#1008 Create index.md
  content/zh/blog/kusionstack-in-practice-at-ant-group-first/index.md
Labels: size/L, cla:yes, First-time contributor

#965 Sofa ark 启动过程源码解析
  content/zh/projects/sofa-boot/sofa-ark-startup-process/1.jpg
  content/zh/projects/sofa-boot/sofa-ark-startup-process/2.jpg
  content/zh/projects/sofa-boot/sofa-ark-startup-process/3.jpg
  content/zh/projects/sofa-boot/sofa-ark-startup-process/index.md
Labels: cla:yes, First-time contributor, size/XL

#1011 update qrcode
  data/zh/footer.toml
  static/img/qrcode/dingtalk_7.jpg
Labels: cla:yes, size/XS

#1010 Create index.md
  content/zh/sofa-weekly-20220826/index.md
Labels: cla:yes, size/M

#1012 Create index.md
  content/zh/blog/go-code-city-cloud-kusionstack-practice/index.md
Labels: size/L, cla:yes
