Repository sofastack/sofastack.tech, pull requests merged in 2022-02, with the labels that each got.

#819 Create index.md
  content/zh/blog/welcome-the-year-of-the-tiger-open-source-is-the-time/index.md
Labels: size/L, cla:yes

#820 Create index.md
  content/zh/blog/sofa-weekly-20220204/index.md
Labels: cla:yes, size/M

#826 Create index.md
  content/zh/blog/sofa-weekly-20220211/index.md
Labels: size/L, cla:yes

#827 Create index.md
  content/zh/blog/application-runtime-layotto-into-cncf-cloud-native-panorama/index.md
Labels: cla:yes, size/M

#828 SOFATracker -> SOFATracer -- spelling fix
  content/en/projects/sofa-tracer/overview/index.md
Labels: cla:yes, size/XS, bug, First-time contributor

#829 Update index.md
  content/zh/projects/sofa-jraft/overview/index.md
Labels: cla:yes, size/XS

#831 Create index.md
  content/zh/blog/sofa-weekly-20220218/index.md
Labels: size/L, cla:yes

#833 Clean wrong markdown and add new contributors and end users.
  content/zh/awesome/_index.md
  content/zh/blog/2021-cloud-native-technology-development-status-and-future-trends/index.md
  content/zh/blog/2021sale-antmonitor-roundup-cloud-native-prometheus-monitoring-in-practice/index.md
  content/zh/blog/ant-groups-10000-scale-k8s-cluster-etcd-high-availability-construction-road/index.md
  content/zh/blog/service-mesh-end-user-survey-report/index.md
  content/zh/blog/sofa-weekly-20210521/index.md
  content/zh/blog/tengine-babassl-making-state-secrets-easier-to-use/index.md
  content/zh/prometheus-on-ceresdb-evolutionary-path/index.md
Labels: cla:yes, size/XL

#834 Create index.md
  content/zh/activities/sofa-channel-25/index.md
Labels: cla:yes, size/M

#835 Create index.md
  content/zh/blog/sofa-weekly-20220228/index.md
Labels: size/L, cla:yes
