Repository sofastack/sofastack.tech, pull requests merged in 2022-05, with the labels that each got.

#893 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-push-switch/index.md
Labels: size/L, cla:yes

#894 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-non-destructive-o-and-m/index.md
Labels: size/L, cla:yes

#895 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#896 Create index.md
  content/zh/blog/sofa-weekly-20220506/index.md
Labels: size/L, cla:yes

#902 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-publish-subscription-push/index.md
Labels: cla:yes, size/XL

#903 Create index.md
  content/zh/projects/sofa-registry/code-analyze/code-analyze-registry-meta/index.md
Labels: size/L, cla:yes

#904 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/S

#905 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS

#900 Create index.md
  content/zh/blog/open-source-summer-2022-welcome-to-the-sofastack-community-and-mosn-community-projects/index.md
Labels: size/L, cla:yes

#901 Create index.md
  content/zh/blog/sofaserverless-system-for-speedy-business-development/index.md
Labels: size/L, cla:yes

#911 add review-and-prospect-of-service-mesh-progress-in-antgroup
  content/zh/blog/review-and-prospect-of-service-mesh-progress-in-antgroup-2022/index.md
Labels: size/L, cla:yes

#912 Create index.md
  content/zh/activities/sofa-meetup-15/index.md
Labels: cla:yes, size/M

#919 Create index.md
  content/zh/blog/sofa-weekly-20220520/index.md
Labels: cla:yes, size/M

#920 Create index.md
  content/zh/blog/deeperinto-http-3-2-the-not-so-boring-ssl/index.md
Labels: size/L, cla:yes

#923 Create index.md
  content/zh/blog/sofa-weekly-20220527/index.md
Labels: cla:yes, size/M

#922 Create index
  content/zh/activities/sofa-channel-27/index.md
Labels: cla:yes, size/M
