Repository sofastack/sofastack.tech, pull requests merged in 2022-09, with the labels that each got.

#1014 Delete content/zh/activities/2022-IOSF directory
  content/zh/activities/2022-IOSF/index.md
Labels: cla:yes, size/S

#1015 Create index.md
  content/zh/blog/sofa-weekly-20220909/index.md
Labels: cla:yes, size/M

#1013 Update index.md
  content/zh/projects/sofa-registry/overview/index.md
Labels: cla:yes, size/XS

#1016 Create index.md
  content/zh/blog/is-pprof-enough-for-go-memory-leak/index.md
Labels: size/L, cla:yes

#1020 Create index.md
  content/zh/blog/sofa-weekly-20220916/index.md
Labels: cla:no, size/M, First-time contributor

#1021 Create index.md
  content/zh/activities/sofa-talk-1/index.md
Labels: cla:yes, size/M

#1025 Create index.md
  content/zh/blog/sofa-weekly/20220923/index.md
Labels: cla:yes, size/M

#1026 Add new contributors.
  content/zh/awesome/_index.md
  content/zh/blog/babassl-support-for-semi-homomorphic-encryption-algorithm-ec-elgamal/index.md
  content/zh/blog/community-article-mosn-community-performance-analysis-tool-holmes-principle-analysis/index.md
  content/zh/blog/sofa-weekly-20220826/index.md
Labels: size/L, cla:yes

#1029 Create index.md
  content/zh/blog/what-have-we-learned-from-scale-platform-engineering-practices/20220927/index.md
Labels: size/L, cla:yes
