Repository sofastack/sofastack.tech, pull requests merged in 2022-01, with the labels that each got.

#809 Create index.md
  content/zh/blog/service-grid-defines-a-new-path-for-enterprises-to-the-cloud-forrester-ant-group-releases-service-grid-white-paper/index.md
Labels: size/L, cla:yes

#810 Create index.md
  content/zh/blog/sofa-weekly-20220107/index.md
Labels: size/L, cla:yes

#811 Create index.md
  content/zh/tengine-babassl-making-state-secrets-easier-to-use/index.md
Labels: size/L, cla:yes

#812 Create index.md
  content/zh/blog/sofa-weekly-20220114/index.md
Labels: size/L, cla:yes

#813 Create index.md
  content/zh/blog/ant-massive-sigma-cluster-etcd-splitting-in-practice/index.md
Labels: size/L, cla:yes

#814 Create index.md
  content/zh/activities/sofa-channel-24/index.md
Labels: cla:yes, size/M

#815 Update index.md
  content/zh/activities/sofa-channel-24/index.md
Labels: cla:yes, size/XS

#816 Create index.md
  content/zh/blog/sofa-weekly-20220121/index.md
Labels: size/L, cla:yes

#817 Create index.md
  2021sale-antmonitor-roundup-cloud-native-prometheus-monitoring-in-practice/index.md
Labels: size/L, cla:yes

#818 Create index.md
  content/zh/blog/sofa-weekly-20220129/index.md
Labels: size/L, cla:yes
