Repository sofastack/sofastack.tech, pull requests merged in 2023-05, with the labels that each got.

#1138 Update index.md
  content/zh/blog/sofa-weekly-20221007/index.md
Labels: cla:yes, size/M

#1139 Create index.md
  content/zh/blog/sofa-weekly-20221111/index.md
Labels: cla:yes, size/M

#1147 Create index.md
  content/zh/blog/sofa-weekly-20230210/index.md
Labels: cla:yes, size/M

#1148 Create index.md
  content/zh/blog/sofa-weekly-20230217/index.md
Labels: cla:yes, size/M

#1150 Create index.md
  content/zh/blog/sofa-weekly-20230324/index.md
Labels: cla:yes, size/M

#1146 Create index.md
  content/zh/blog/moe-series (3)｜dynamic-update-of-go-extension-configuration-with-istio/index.md
Labels: size/L, cla:yes

#1152 Create index.md
  content/zh/blog/sofa-weekly-0505/index.md
Labels: size/L, cla:yes

#1153 Create index.md
  content/zh/activities/open-source-promotion-plan-2023-welcome-to-the-sofastack-community-project/index.md
Labels: size/L, cla:yes

#1154 Create index.md
  content/zh/activities/open-source-promotion-plan-2023-welcome-to-the-mosn-community-project!/index.md
Labels: size/L, cla:yes

#1158 Create index.md
  content/zh/blog/sofa-weekly-230512/index.md
Labels: cla:yes, size/M

#1159 Create index.md
  content/zh/activities/[Summer-2023-of-open-source-promotion-plan]welcome-to-register-for-dragonfly,kata-containers,and-nydus-community-projects!/index.md
Labels: size/L, cla:yes

#1160 Create index.md
  content/zh/blog/moe-series (4)-go-extended-asynchronous-mode/index.md
Labels: size/L, cla:yes

#1161 Create index.md
  content/zh/blog/sofa-weekly-20230428/index.md
Labels: size/L, cla:yes

#1162 Create index.md
  content/zh/blog/sofa-weekly-20230414/index.md
Labels: cla:yes, size/M

#1163 Update index.md
  content/zh/blog/moe-series (3)｜dynamic-update-of-go-extension-configuration-with-istio/index.md
Labels: cla:yes, size/XS

#1164 Create index.md
  content/zh/blog/sofa-weekly-20230407/index.md
Labels: size/L, cla:yes

#1166 Create index.md
  content/zh/blog/origins｜ant's-practical-path-to-application-level-service-discovery/index.md
Labels: size/L, cla:yes

#1167 Create index.md
  content/zh/blog/moe-series (1)|how-to-extend-envoy-with-golang/index.md
Labels: size/L, cla:yes

#1169 Create index.md
  content/zh/blog/volcano-engine-based-on-dragonfly-acceleration-practices/index.md
Labels: size/L, cla:yes

#1170 Create index.md
  content/zh/blog/sofa-weekly-230519/index.md
Labels: cla:yes, size/M

#1168 Create index
  content/zh/projects/sofa-registry/code-analyze/sofaregistry-talk-about-the-data-consistency-of-service-discovery/index.md
Labels: cla:yes, size/XL

#1171 Create index.md
  content/zh/projects/sofa-registry/code-analyze/origins-ant-s-practical-path-to-application-level-service-discovery/index.md
Labels: size/L, cla:yes

#1172 Create index.md
  content/zh/blog/mosn-delay-based-load-balancing-algorithm-go-faster, expect-to-go-steadier/index.md
Labels: size/L, cla:yes

#1173 Create index.md
  content/zh/blog/Go-language-how-to-do-inverse-type-derivation/index.md
Labels: size/L, cla:yes

#1174 Create index.md
  content/zh/blog/nydus-container-image-acceleration-practices-on-the-yosemite-platform/index.md
Labels: size/L, cla:yes

#1175 Create index.md
  content/zh/blog/seata-go-1-1-0-released-completes-at-mode-support/index.md
Labels: size/L, cla:yes

#1176 Create index1.md
  content/zh/blog/volcano-engine-based-on-dragonfly-acceleration-practices/index1.md
Labels: size/L, cla:yes

#1178 Update _index.md
  content/zh/projects/sofa-registry/_index.md
Labels: cla:yes, size/XS
