Repository sofastack/sofastack.tech, pull requests merged in 2023-02, with the labels that each got.

#1102 Create index.md
  content/zh/blog/sofa-weekly-20230127/index.md
Labels: cla:yes, size/M

#1103 Create index.md
  content/zh/blog/sofa-special-weekly/index.md
Labels: cla:yes, size/M

#1104 Create index.md
  content/zh/blog/nudus-20230131/index.md
Labels: size/L, cla:yes

#1105 Create index.md
  content/zh/blog/sofa-weekly-20230203/index.md
Labels: cla:yes, size/M

#1106 Add new contributors.
  content/p2p-transfer-protocol-optimization-in-dragonfly/index.md
  content/zh/awesome/_index.md
  exploratory-practice-of-heterogeneous-registration-centre-mechanism-in-icbc/index.md
Labels: size/L, cla:yes

#1107 Add layotto to projects.
  content/en/projects/layotto/_index.md
  content/zh/projects/layotto/_index.md
  static/img/icons/layotto.png
Labels: cla:yes, size/S

#1108 Create index.md
  content/zh/activities/sofa-channel-32/index.md
Labels: cla:yes, size/M

#1109 Create index.md
  content/zh/activities/sofachannel-32/index.md
Labels: cla:yes, size/M

#1110 Change the SOFABoot quickstart to annotation
  content/en/projects/sofa-rpc/getting-started-with-sofa-boot/index.md
  content/en/projects/sofa-rpc/programing-sofa-boot-annotation/index.md
  content/en/projects/sofa-rpc/programing-sofa-boot-xml/index.md
  content/zh/projects/sofa-rpc/getting-started-with-sofa-boot/index.md
  content/zh/projects/sofa-rpc/programing-sofa-boot-annotation/index.md
  content/zh/projects/sofa-rpc/programing-sofa-boot-xml/index.md
Labels: size/L, cla:yes

#1114 Create index.md
  content/zh/blog/index.md
Labels: cla:no, size/M, First-time contributor
