Repository sofastack/sofastack.tech, pull requests merged in 2023-09, with the labels that each got.

#1222 Create index.md
  content/zh/activities/sofa-channel-35/index.md
Labels: cla:yes, size/M

#1223 Create index.md
  content/zh/blog/sofa-weekly-20230901/index.md
Labels: size/L, cla:yes

#1225 fix sofa-boot-config
  content/zh/projects/sofa-boot/_index.md
Labels: cla:yes, size/XS, bug

#1224 Create index.md
  content/zh/blog/sofa-weekly-20230825/index.md
Labels: size/L, cla:yes

#1227 Create index.md
  content/zh/blog/elephant-turn-summary-of-alipay-funding-technology-serverless-efficiency-improvements/index.md
Labels: size/L, cla:yes

#1228 Update index.md
  content/zh/activities/sofa-channel-35/index.md
Labels: cla:yes, size/M

#1229 Create index.md
  content/zh/blog/sofa-weekly-20230915/index.md
Labels: size/L, cla:yes

#1230 feat:图片加载失败问题
  content/zh/activities/sofa-channel-29/index.md
  content/zh/activities/sofa-channel-30/index.md
  content/zh/activities/sofa-channel-31
  content/zh/activities/sofa-channel-32/index.md
  content/zh/activities/sofa-channel-33/index.md
  content/zh/activities/sofa-channel-34/index.md
  content/zh/activities/sofa-meetup-16/index.md
  content/zh/activities/sofa-meetup-17/index.md
  content/zh/activities/sofachannel-31/index.md
  layouts/partials/post/article.html
Labels: cla:no, cla:yes, size/M, First-time contributor

#1231 Dev/tong
  content/en/projects/sofa-dashboard/overview/index.md
  content/zh/projects/sofa-dashboard/ark-console/index.md
  content/zh/projects/sofa-dashboard/overview/index.md
  layouts/partials/post/article.html
Labels: cla:yes, size/M
