Repository sofastack/sofastack.tech, pull requests merged in 2023-08, with the labels that each got.

#1204 Create index.md
  content/zh/blog/moe-series (7) |envoy-go-extension-sandbox-security/index.md
Labels: cla:yes, size/M

#1205 1
  content/zh/blog/moe-series（6）｜envoy-go-extensions- concurrency- security/index.md
Labels: cla:yes, size/M

#1203 Create index.md
  content/zh/blog/sofaboot-4.0-is-officially-released-with-many-new-features-for-you-to-experience/index.md
Labels: cla:yes, size/XL

#1207 Delete index.md
  content/zh/blog/sofaboot-4-0-is-officially-released-with-many-new-features-for-you-to-experience/index.md
Labels: cla:yes, size/XL

#1212 Create index.md
  content/zh/blog/dragonfly-v-2-1-0-release/index.md
Labels: size/L, cla:yes

#1213 Create index.md
  content/zh/blog/sofa-weekly-20230818/index.md
Labels: cla:yes, size/M

#1214 Create index.md
  content/zh/activities/sofa-channel-34/index.md
Labels: cla:yes, size/M

#1215 fix imgage picture failure
  assets/js/app.js
  layouts/partials/post/article.html
Labels: cla:yes, bug, size/S

#1217 Create index.md
  content/zh/blog/ant-group-sofa-serverless-new-microservices-architecture-exploration-and-practice/index.md
Labels: size/L, cla:yes

#1219 image error fix
  layouts/partials/post/article.html
Labels: cla:yes, bug, size/S

#1221 Create index.md
  content/zh/projects/sofa-boot/upgrade_4_x/index.md
Labels: cla:yes, size/XL
