Repository sofastack/sofastack.tech, pull requests merged in 2023-06, with the labels that each got.

#1183 Create index.md
  content/zh/blog/moe-series (5)｜envoy-go-extensions-memory-security/index.md
Labels: cla:yes, size/M

#1184 Create index.md
  content/zh/activities/sofa-channel-33/index.md
Labels: cla:yes, size/M

#1181 修正了几个yaml语法错误导致的hugo编译错误,
  content/zh/blog/mosn-delay-based-load-balancing-algorithm-go-faster, expect-to-go-steadier/index.md
  content/zh/blog/origins｜ant's-practical-path-to-application-level-service-discovery/index.md
  content/zh/blog/volcano-engine-based-on-dragonfly-acceleration-practices/index.md
  content/zh/projects/sofa-registry/code-analyze/origins-ant-s-practical-path-to-application-level-service-discovery/index.md
  content/zh/projects/sofa-registry/code-analyze/sofaregistry-talk-about-the-data-consistency-of-service-discovery/index.md
Labels: cla:yes, size/S, First-time contributor

#1191 Create index.md
  content/zh/blog/sofa-weekly-230616/index.md
Labels: cla:yes, size/M

#1190 Create index.md
  content/zh/blog/sofa-weekly-230609/index.md
Labels: cla:yes, size/M

#1192 Update index.md
  content/zh/blog/sofa-weekly-20230407/index.md
Labels: cla:yes, size/XS

#1193 Update index.md
  content/zh/blog/sofa-weekly-20230414/index.md
Labels: cla:yes, size/XS

#1194 Create index.md
  content/zh/blog/the-next-five-years-of-sofastack/index.md
Labels: size/L, cla:yes, First-time contributor
