Repository sofastack/sofastack.tech, pull requests merged in 2024-03, with the labels that each got.

#1254 完善服务发布与引用
  content/zh/projects/sofa-rpc/publish-and-reference/index.md
Labels: cla:yes, size/M

#1252 typo fix
  content/zh/blog/sofa-registry-introduction/index.md
Labels: cla:yes

#1253 fix formatting
  content/zh/blog/sofa-registry-introduction/index.md
Labels: cla:yes, size/XS

#1255 修复注册中心扩展指南
  content/zh/projects/sofa-rpc/registry-extension-guide/index.md
Labels: cla:yes, size/XS

#1258 Create index.md
  content/zh/blog/economical-and-efficient-enhance-the-competitiveness-of-enterprises-sofaserverless-brand-upgraded-to-koupleless-release-version-1.0/index.md
Labels: size/L, cla:yes

#1257 Create index.md
  content/zh/blog/efficient-cost-reduction-case-study-of-koupleless-practical-application-in-nanjing-f6/index.md
Labels: size/L, cla:yes

#1259 docs: 修复文档序号错乱
  content/zh/projects/sofa-rpc/getting-started-with-sofa-boot/index.md
Labels: cla:no, cla:yes, size/XS, First-time contributor

#1260 Create index
  content/zh/blog/open-source-together-seata-enters-apache-incubator/index.md
Labels: size/L, cla:yes

#1261 Create index.md
  content/zh/blog/ospp-exprience-sharing-keep-enthusiastic-and-all-in/index.md
Labels: size/L, cla:yes

#1262 Create index.md
  content/zh/blog/say-goodbye-to-complexity-easily-tackle-k8s-management-challenges-with-the-right-tools/index.md
Labels: cla:yes, size/M

#1263 Create index.md
  content/zh/blog/ospp-experience-sharing-community-contribution-is-a-kind-of-influence/index.md
Labels: size/L, cla:yes

#1256 自动编译上传阿里云的action文件
  .github/workflows/oss.yml
Labels: cla:yes, size/S, First-time contributor

#1265 fix integration start_dev path
  content/zh/projects/sofa-registry/server-quick-start/index.md
Labels: cla:yes, size/XS, bug

#1264 Create index.md
  content/zh/blog/explore-the-workflow-of-mosn-from-an-rpc-request/index.md
Labels: size/L, cla:yes

#1266 Create index.md
  content/zh/blog/koupleless-brings-split-plugin-to-help-you-to-improve-the-efficiency-of-collaborative-development/index.md
Labels: size/L, cla:yes
