Repository sofastack/sofastack.tech, pull requests merged in 2024-10, with the labels that each got.

#1293 fix image show
  layouts/partials/post/article.html
Labels: cla:yes, size/XS, bug

#1188 add classLoaderHook introduce
  content/zh/projects/sofa-boot/sofa-ark-ark-extension/index.md
Labels: cla:yes, size/S

#1282 refer and add koupleless Samples
  content/en/projects/sofa-boot/sofa-ark-readme/index.md
  content/zh/projects/sofa-boot/sofa-ark-class-loader-delegation/index.md
  content/zh/projects/sofa-boot/sofa-ark-migration-guide/index.md
  content/zh/projects/sofa-boot/sofa-ark-readme/index.md
Labels: cla:yes, size/M

#1294 Create index.md
  content/zh/blog/tuya-smart-implements-merged-deployment-with-koupleless-to-achieve-cost-saving-and-profit-increasing-in-cloud-services/index.md
Labels: size/L, cla:yes
