Repository sofastack/sofastack.tech, pull requests merged in 2024-05, with the labels that each got.

#1273 Create ospp-2024-open-source-programs-for-college-students
  content/zh/blog/ospp-2024-programs-for-college-students
Labels: size/L, cla:yes

#1274 Update index.md
  content/zh/projects/sofa-registry/client-quick-start/index.md
Labels: cla:yes

#1275 修复博客页面展示错误问题
  layouts/partials/aside/project.html
  layouts/partials/card/project_card.html
  layouts/partials/card/toc_list_card.html
  layouts/partials/pagination/pagination_next.html
  layouts/partials/toc/toc_leaf.html
  layouts/projects/section.html
Labels: size/L, cla:yes, First-time contributor

#1276 官网转换
  .github/workflows/hugo.yml
  data/zh/home.toml
Labels: cla:yes, size/M

#1279 mdl校验修改
  .circleci/config.yml
  .github/workflows/hugo.yml
  content/zh/activities/sofa-anniversary-6/index.md
  content/zh/blog/index.md
  content/zh/guides/kc-cloud-mesh-demo/index.md
  content/zh/guides/kc-seata-demo/index.md
  content/zh/guides/kc-serverless-demo/arch.jpg
  content/zh/guides/kc-serverless-demo/index.md
  content/zh/guides/kc-serverless-demo/kc-sas.jpg
  content/zh/guides/kc-serverless-demo/preview-sas.png
  content/zh/guides/kc-sofastack-dynamic-demo/index.md
  content/zh/guides/sofastack-demos/index.md
  content/zh/guides/sofastack-quick-start/index.md
  scripts/mdl-check.sh
Labels: cla:yes, size/XXL
